GoogleCloudDataproc/initialization-actions

- apache-zeppelin/README.MD
- apache-zeppelin/zeppelin.sh
A couple of customers asked directions to Cloud Support on how to install Apache Zeppelin on Dataproc. I have created a init script and it would be nice to have it in this repository.
> Add Apache Zeppelin initialization action

- conda/bootstrap-conda.sh
- jupyter/internal/setup-jupyter-kernel.sh
additionally, allow MINICONDA_VARIANT to be defined by GCE metadata.
> Fix failure when JUPYTER_PORT not specified

- stackdriver/README.md
Add a note to include required stackdriver scopes with a link to further
stackdriver monitoring documentation; add suggestion to use unique tags to
more easily identify clusters for stackdriver dashboard creation.
> Fix stackdriver installation instructions.

- post-init/README.md
- post-init/master-post-init.sh
This initialization action can be used as either an initialization action or as a startup-script,
with the latter enabling support for commands which need to be re-run on reboot. This
initialization action adds polling for the cluster itself to be fully healthy before issuing
a command, effectively allowing "post-initiailization" actions which can include further setup
or submitting a job.
> Add a new post-init helper script.

- jupyter/internal/setup-jupyter-kernel.sh
This preserves the behavior of 4.2.3 from a couple weeks ago; GCE firewalls
rules with SSH tunnels are the recommended way to handle security, and
the default token-generation behavior is unwieldy/unnecessary. Keep a
metadata entry in case the user wants to specify a token regardless.
> Disable Jupyter token auth by default.

- jupyter/README.MD
- jupyter/jupyter.sh
Takes colon-separated list of conda packages to install before Jupyter setup.
For example, --metadata JUPYTER_CONDA_PACKAGES=numpy:pandas will now install
numpy and pandas on all cluster nodes. Also update the README with both
simplified basic instructions as well as instructions for using the new
metadata option.
> Add a JUPYTER_CONDA_PACKAGES metadata option.

- flink/flink.sh
The flink download links were broken and some configuration variables were set incorrectly. This action now installs flink via apt-get and only runs on the master.
> Fix flink init action.

- datalab/datalab.sh
This change adds an additional volume mount to the Datalab initialization action that maps "/content/datalab" from the Datalab container into the VM's persistent disk.
This fixes #92
> Add a volume mount for notebooks

- README.md
- drill/README.md
- drill/drill.sh
Lightly tested. Out-of-box works with the default dataproc GCS bucket, HDFS, local linux fs (not really very useful!) and Hive.
> add apache drill initialization action

- conda/bootstrap-conda.sh
- conda/install-conda-env.sh
- jupyter/jupyter.sh
This is a much needed cleanup of the conda bootstrap init action, specifically, by:
- conforming to default pathing + .profile script names in docker image at continuumio/miniconda3
- removing all conda updates (eliminating breaking version updates)
- making idempotent the conda .profile modifications
> conda bootstrap cleanup

- drill/drill.sh
Made the following changes recommended from #98:
- Find the GCS connector by wildcard for version-proofing
- Maybe derive Hive and HDFS settings from *-site.xml files
- Derive zookeeper node list and client port from /etc/zookeeper/conf
- Move drill profile to a subdirectory of dataproc bucket that has cluster uuid
- on a failure after starting the drillbit, cat the logs for troubleshooting
> enhancements from #98

- conda/bootstrap-conda.sh
-Allow setting MINICONDA_VARIANT by metadata again
-Fix variable existence checks to accommodate for this
-Also add MINICONDA_VERSION as metadata option
-Rename MINICONDA_VER to MINICONDA_VERSION
> Pin default miniconda version to 4.2.12.

- kafka/kafka.sh
The default log (data) folder gets wiped on reboot in Debian/Ubuntu. It is better to move it to somewhere else (see http://stackoverflow.com/a/32439885).
> Fix Kafka data loss on reboot

- kafka/README.MD
- kafka/kafka.sh
Make it more resilient to different zookeeper installations, and prefer
to use Dataproc HA to provide zookeeper masters. Add end-to-end
example.
> Refactor kafka.sh to install from dataproc distro.

- jupyter/internal/launch-jupyter-kernel.sh
Per https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/issues/108
For testing this, is the following the right strategy?
1. Edit jupyter.sh to point at my branch
2. Push jupyter.sh to GCS
3. Run gcloud dataproc clusters create
> Autostart Jupyter on node restart

- jupyter/jupyter.sh
By prepolutating a metadata value at cluster creation, it is
possible to setup additional channels from which to pull packages in Conda.
> jupiter.sh: Add support for conda channels

- flink/README.md
- flink/flink.sh
The yarn session is currently configured to consume all YARN resources. This makes it difficult to submit non-flink jobs to a cluster that has been started with the flink init action.
This change disables the default session. Users can always fork the script to change this setting or manually initiate their own sessions out-of-band.
> Disable long-running flink yarn session by default.

- flink/README.md
- flink/flink.sh
This allows the default behavior (whether or not a detached yarn session should be started) to be overridden based on the value of attributes/flink-start-yarn-session.
This change also fixes the jobmanager RPC address. This value was previously not being filled because the MASTER_HOSTNAME environment variable was unbound.
> Gate flink yarn session on GCE metadata

- zeppelin/zeppelin.sh
The init action appears to be broken as-is due to a transitive dependency change.
> Update apt repos before installing zeppelin

- flink/flink.sh
The Flink init action currently installs Flink on all masters and attempts to start a YARN session on all masters. Because this default session is configured to consume all cluster resources, all but one of the master init actions hang indefinitely while trying to allocate containers.
This change only installs and runs Flink on the primary master.
> Only install Flink on primary master

- conda/README.MD
* Remove PYTHONHASHSEED hack, as the relevant Spark bug has been fixed
in Dataproc 1.2 (the new default image)
* Make first usage example clearer
* Fix conda env path
> Update conda readme

- presto/presto.sh
I'm getting an error
```
Query ... failed: Failed connecting to Hive metastore: [localhost:9083]
```
It looks like using `localhost` for `hive.metastore.uri` is a mistake because there is probably no hive metastore on workers.
`/etc/hive/conf/hive-site.xml` also uses the name of a specific machine for `hive.metastore.uris`.
> Fix `hive.metastore.uri` and upgrade Presto

- README.md
Importantly, document init actions that do not work on single node clusters.
> Update README with single node information

- README.md
- hue/hue.sh
- oozie/oozie.sh
In hue init action: add hue as proxy user for oozie if oozie is installed
In oozie init action: change where ext library installed, install share lib, get rid of reboot, other small fixes
Depends on bigtop change in latest release
> Fixes to oozie and hue init actions

- flink/flink.sh
The init action uses `set -e` to fail if any setup actions fail (i.e., exit non-zero). The script used to fetch metadata exits non-zero if the attribute requested does not exist. We use a metadata attribute to determine whether to start a detached yarn session. This causes the init action to fail if the special attribute is not set (the default behavior).
> Fix flink init action (#155)

- tez/tez.sh
Hello,
tez-ui won't start cause of old nodejs available in debian-jessie repos.
nodejs v0.10.x doesn't support `const`.
here is the output of `/var/log/tez-ui.log`with related error: 
```
/usr/local/lib/node_modules/http-server/node_modules/ecstatic/lib/ecstatic.js:5
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/usr/local/lib/node_modules/http-server/lib/http-server.js:5:16)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
error: …
```
> tez-ui.sh, update nodejs to v8

- jupyter/README.MD
- jupyter/internal/setup-jupyter-kernel.sh
- jupyter/jupyter.sh
This is a counterproposal to #154 (cc @waltherg). Instead of copying the files back and forth to GCS, just use this [cool project](https://github.com/src-d/jgscm) to read/save files directly in GCS.
CC @vmarkovtsev as the maintainer of jgscm. You mention that jgscm is in in alpha state -- I just want to check whether you have any concerns about this PR. For what it's worth, at least Python3 "hello world" worked for me.
> Only store Jupyter notebooks in GCS.

- datalab/datalab.sh
- flink/flink.sh
- ganglia/ganglia.sh
- hue/hue.sh
- jupyter/internal/bootstrap-jupyter-ext.sh
- kafka/kafka.sh
- oozie/oozie.sh
- tez/tez.sh
- user-environment/user-environment.sh
- zeppelin/zeppelin.sh
- zookeeper/zookeeper.sh
Fixes #168 (init actions occasionally fail because `apt-get update` fails)
I added `update_apt_get` to all init actions that run `apt-get install`, as we have also seen occasional init action failures because apt-get update was not run.
> Run apt-get update on all init actions with retries

- zeppelin/zeppelin.sh
As per https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/issues/190 following topics are covered:
- consistent indentation
- moved constants to top of the file
- add err function and log installation problems
- add systemd config
- main function
I'm also wondering what to do with this commented-out block of code related to `mplot` and `rCharts` . Was it ever used? It could be changed to be run only if some appropriate metadata key is set, but currently it doesn't work when uncommented.
> Adjust Zeppelin init action to conform the guidelines.

- conda/README.MD
- conda/bootstrap-conda.sh
Fixes #149 
This change checks whether Spark version is >= 2.2.0 and if so sets the Miniconda version to the latest version. If Spark is < 2.2.0 then the existing behavior is unchanged: pin Miniconda to 4.2.12
This change should resolve the following issue once merged with the main repo:
GoogleCloudPlatform#149
This change also includes some formatting fixes to README.MD: the bullet points in the markdown don't render correctly on github.
> Use latest miniconda version if Spark >= 2.2.0

- connectors/README.md
- connectors/connectors.sh
Starting from the next release (1.8.0/0.12.0), GCS and BigQuery connectors will be fully independent and it will be possible to mix them from different releases, that's why there no need to forcefully update both of them simultaneously.
> Allow to update GCS and BigQuery connectors independently

- zeppelin/zeppelin.sh
This PR is follow-up for #191 that was reverted in #209. As per discussion in #209 I removed additional systemd config file in favor of the one installed by apt-get.
I'm however still not sure if we should simply abandon it. The main benefit of custom `zeppelin.service` is that it contained `Restart=always` clause that is not there in the pre-installed configs. What's more it seems to be hard to change (i.e. via sed) because `Restart=no` seems to be hardcoded in sysv-generator as can be seen here: 
https://github.com/systemd/systemd/blob/master/src/sysv-generator/sysv-generator.c#L179
(it's pointig to master, but this line was the same for last 4 years ;)
I didn't find a way to change this configuration and if we want to have auto-restarting Zeppelin I'd suggest to bring back previous …
> refactored Zeppelin init action

- jupyter/README.MD
- jupyter2/README.md
- jupyter2/jupyter2.sh
The Jupyter init action does its job, but is a little confusing to use:
* It invokes the Conda init action(s) by git cloning this repo. It also invokes sub-scripts through this cloned copy of the repo. So any changes to the sub-scripts involve pointing the main init action script at a different git repository.
* It switches to Python 3. Because of this you lose all of the packages pre-installed by Dataproc, like `numpy`. So a script that works in `gcloud dataproc jobs submit pyspark` does not work out of the box in Jupyter. Issue #174 is an example of when this bites you.
* Note that Jupyter comes with the `six` library, which lets you run most python 2 or 3 code against either version of python. So leaving python at python2 hopefully shouldn't be a big deal for python3 users.
* The …
> Proposal: A simpler Jupyter init action (design review wanted)

- jupyter/jupyter.sh
Reverts GoogleCloudPlatform/dataproc-initialization-actions#237
Reverting this PR because it does not work on Dataproc 1.0/1.1. E.g.
```
Successfully built jgscm gcloud tornado httplib2 googleapis-common-protos backcall
Installing collected packages: httplib2, setuptools, six, protobuf, googleapis-common-protos, pyasn1, pyasn1-modules, rsa, oauth2client, gcloud, tornado, jupyter-core, python-dateutil, pyzmq, jupyter-client, parso, jedi, decorator, backcall, pexpect, ipython, ipykernel, terminado, jinja2, testpath, webencodings, html5lib, bleach, mistune, nbconvert, Send2Trash, notebook, jgscm, cycler, pytz, numpy, kiwisolver, matplotlib
Found existing installation: setuptools 27.2.0
Cannot remove entries from nonexistent file /opt/conda/lib/python3.5/site-packages/easy-install.pth
You are …
```
> Revert "Install matplotlib for Jupyter"

- README.md
The current README described what initialization actions are, but it didn't mention why we want to use them. This is important for new Dataproc users like me.
> Add a brief "why use init actions" in README.md

- openssl/README.md
- openssl/openssl.sh
NPN has been deprecated for quite some time with ALPN being its
replacement. OpenSSL 1.0.1, which is included in Debian 8, does not
support ALPN, only NPN. OpenSSL 1.0.2 supports ALPN.
This initialization action installs OpenSSL 1.0.2 from jessie backports.
Using this initialization action can be useful if using gRPC with
netty-tcnative-dynamic libraries and encountering NPN / ALPN negotation
failures when communicating with Google services from Dataproc clusters.
> Add an initialization action to install OpenSSL 1.0.2 from backports.

- README.md
- bigdl/README.md
- cloud-sql-proxy/README.MD
- conda/README.MD
- connectors/README.md
- datalab/README.md
- drill/README.md
- flink/README.md
- ganglia/README.MD
- gobblin/README.md
- hive-hcatalog/README.md
- hue/README.md
- jupyter/README.MD
- jupyter2/README.md
- kafka/README.MD
- livy/README.md
- oozie/README.MD
- presto/README.MD
- rstudio/README.MD
- stackdriver/README.md
- tez/README.MD
- user-environment/README.MD
- zeppelin/README.MD
- zookeeper/README.MD
* Only mention copying init actions to GCS in top-level README.
Component READMEs only mention using
gs://dataproc-initialization-actions
* Add all supported init actions to top level README
* Fix minor stylistic nitpicks
* Extra newline after any heading
* Numbered bullets repeatedly use "1. 1." rather than "1. 2. etc"
* Consistent names for sections like "Important notes" and "Using this
initialization action"
* Removed mentions of init action timeouts, as the server timeout has
increased to 10 minutes
* Make the Jupyter init action README a little bit easier to digest
> Improve consistency of init action READMEs

- zookeeper/zookeeper.sh
Fixed problem with /var/lib/zookeeper/myid file that contains node name instead just simple number.
For valid zookeeper configuration it should be myid prepared as there https://stackoverflow.com/a/11498597
> Fixed overwrite problem with zookeeper

- connectors/connectors.sh
Dataproc Agent needs to be restarted because it could have loaded classes from old GCS connector jar which could cause failures during job submission.
> Restart Dataproc Agent Service after connectors update.

- drill/README.md
- drill/drill.sh
Review changes #200.
Original action does not allow for single, standard and HA configuration clusters - had to apply some changes to move this on. Now all clusters can be initialized but there are some issues with running drill example. Tested on drill version 1.13 and image-version 1.2.27.
Current state:
- All clusters initialize
- For init action with zookeeper first   (--initialization-actions gs://dataproc-initialization-actions/zookeeper/zookeeper.sh,gs://.../drill/drill.sh  ) Drill sample works only for single node configuration. For others there is an error: 
```
Error: Failure in starting embedded Drillbit: java.net.BindException: Address already in use (state=,code=0)
java.sql.SQLException: Failure in starting embedded Drillbit: java.net.BindException: Address already in use
at …
```
> Drill refactor

- cloud-sql-proxy/README.MD
- cloud-sql-proxy/cloud-sql-proxy.sh
When switching Dataproc versions, metastore schema may become incompatible. When this happens, we can use schematool to report a concise error and fail.
$ /usr/lib/hive/bin/schematool -dbType mysql -info
Hive distribution version:       2.3.0
Metastore schema version:        2.1.0
org.apache.hadoop.hive.metastore.HiveMetaException: Metastore schema version is not compatible. Hive Version: 2.3.0, Database Schema Version: 2.1.0
*** schemaTool failed ***
User can upgrade their schema by running:
$ /usr/lib/hive/bin/schematool -dbType mysql -upgradeSchemaFrom 2.1.0
I am not sure if automating upgrade is a welcome change. Could we potentially upgrade schema in a way that it could no longer be used with previous Dataproc versions?
> Add a check for schema compatibility to cloud-sql-proxy

- cloud-sql-proxy/cloud-sql-proxy.sh
When creating a HA cluster, mysql cli is uninstalled on all masters other than master0, so we can't use mysql cli to setup hive metastore on those nodes. Since all the masters point to the same db in cloud sql as the hive metastore, we need only master0 to setup the metastore, and the other masters only need to update "hive.metastore.warehouse.dir", which can be fetched using beeline to query hive server directly.
> skip hive metastore in cloud sql setup for masters other than master0 in HA mode

- drill/drill.sh
I replaced apache.mirrors.hoobly.com with a link to the archive apache sources. Now init action passes. 
Related to the #299
> Drill url needs to be updated because the old one has expired and is not valid anymore

- flink/README.md
- flink/flink.sh
In order to support Beam use cases, customers need to be able to install
flink versions other than the ones supported by apt.  To facilitate
this, this commit adds the metadata key `flink-snapshot-url` which, when
set, will be used to download a flink tarball from a custom address.
This commit also cleans up the call pattern a little by separating
flink configuration and invocation.  This is useful if the yarn
application needs to be killed and restarted for any reason.
> Allow users to specify a custom Flink snapshot URL

- connectors/connectors.sh
Because Datarpoc Agent deregisters node and after that registers node again during service restart it's better to kill its process instead of restarting service to avoid flakiness introduced by deregistration-registration flow.
Fixes https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/issues/340
> Fix nodes flakiness when using connectors init action

- beam/README.md
- beam/beam.sh
- beam/beam_job_service.sh
- beam/util/build-beam-artifacts.sh
This sets up a Beam Job Service on the master node.  It depends on Flink
and Docker being installed to function correctly.
The Beam team has advised us that Beam is not in a place where the portability
framework can be considered production ready, and as a result the stable
snapshots cannot be relied on.  They advise instead that for the time being,
users build their own Job Service and Worker Image artifacts.  This PR includes
both an init action for the job service, and an automated build script.
Build instructions are also available in the README.
> Add Beam Job Service init action

- beam/README.md
- beam/beam.sh
It turns out that the gcs staging bucket is not managed the way I
thought, making hdfs a better fit for beam artifacts.
> Fix beam artifact path to use hdfs over the gcs staging bucket

- beam/README.md
- beam/beam.sh
There were some unexpected errors when using HDFS for artifact staging.
Until these are resolved, Beam will go back to storing artifacts in the
cluster staging bucket.
> Revert Beam to store artifacts in cluster staging bucket

- secure/README.md
- secure/secure.sh
Provide as many default values as possible.
> Provide default values (and self-signed certificate) if user does not specify them in secure/secure.sh.

- jupyter/internal/setup-jupyter-kernel.sh
`*` isn't accepted as a valid value by the python socket lib anymore. So, updated it to `0.0.0.0` which is backwards compatible with older versions as well.
Signed-off-by: Alex Johnson <ajohnson@bombora.com>
> Change Jupyter remote allowed ip from `*` to `0.0.0.0`

- cloud-sql-proxy/cloud-sql-proxy.sh
The systemctl start may return asynchronously while cloud-sql-proxy
is not yet ready, such that subsequent attempts to initialize the
metastore will fail.
> Add a run_with_retries nc call to sql proxy after starting it.

- jupyter/jupyter.sh
Open issue (https://github.com/pypa/pip/issues/5839) causes pip install to fail with the following message --
File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
req = REQUIREMENT.parseString(requirement_string)
File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1632, in parseString
raise exc
File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1622, in parseString
loc, tokens = self._parse( instring, 0 )
File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3395, in …
> Update jupyter.sh to set testpath<0.4

- oozie/test_oozie.py
- oozie/validate.sh
These scripts can be used for testing Oozie init action on single, standard and ha configurations.
> Oozie integration tests

- hbase/README.md
- hbase/hbase.sh
- hbase/test_hbase.py
Basic integration test for Apache HBase.
Test can be run using:
python -m unittest hbase.test_hbase
> Init action with Apache HBase.

- tez/README.MD
> Added info how to use pre-installed Tez on Dataproc 1.3+ clusters.

- rstudio/rstudio.sh
1) Add --no-tty to `apt-key adv` for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913614
2) Update RStudio apt repository to Debian 9
3) Update RStudio version to 1.1.463
4) Fixes #397
> Fix RStudio init action. 

- secure/README.md
to point out the Kerberos optional component is better supported.
> Update secure/README.md about the Kerberos component

- zookeeper/zookeeper.sh
dataproc-worker-count metadata is no longer valid after scaling the
cluster. We observed the value is 1 for newly added workers which caused
the init action to fail.
> ZooKeeper: remove the check for the number of workers.

- conda/bootstrap-conda.sh
In Dataproc 1.4+, use /etc/profile.d/effective-python.sh;
for older versions, use the /etc/profile/conda.sh.
> Make Conda profile script path backwards compatible.

- drill/drill.sh
Previous link to drill expired with next updates. I replaced this link with not-expiring link valid for 1.15.0 Release.
> Updated Drill version and url

- rstudio/rstudio.sh
This change fixes #426 by updating the Dataproc rstudio init action to use the correct image for Debian 9 based on [the instructions](https://www.rstudio.com/products/rstudio/download-server/). It also ensures that the users and groups do not exist before adding them. Prior to this change, rstudio fails to start because it can't find libssl.so.1.0.0 and libcrypto.so.1.0.0
> Update rstudio init action to use correct package for Debian 9

- jupyter/kernels/install-toree.sh
Path pointed to an outdated, in-development version of toree. It now points to a released version.
>  Corrected path to toree installer

- solr/README.md
- solr/solr.sh
This commit enables SolrCloud mode on HA dataproc clusters.
Solr download link was switched to apache archives to avoid any future installation failures.
SolrCloud configuration is stored in separate zookeeper znode which is recommended for production deployments.
> Solr in HA clusters is now available in SolrCloud mode.

- cloud-sql-proxy/__init__.py
- cloud-sql-proxy/test_cloud_sql.py
To run the test just use command:
python -m unittest cloud-sql-proxy.test_cloud_sql
> Integration test for Cloud SQL proxy init action.

- kafka/kafka.sh
The method 'install_and_configure_kafka_server' can now run on master so the error message explicitly stating it is a 'worker' is not accurate anymore, so get rid of the 'on worker node' part.
> Update Kafka.sh error message

- integration_tests/README.MD
- integration_tests/dataproc_test_case.py
Using [python3-fastunit](https://github.com/ityoung/python3-fastunit) helps to run integration tests in parallel, while still allowing to run them normally.
Using standard `unittest` module:
```
$ python -m unittest hive-hcatalog.test_hive
............
Ran 12 tests in 3547.914s
```
Using `fastunit` module:
```
$ python -m fastunit hive-hcatalog.test_hive
............
Ran 12 tests in 324.939s
```
> use python3-fastunit to allow to run tests in parallel

- oozie/oozie.sh
This fix repairs problem with not available oozie web console when ext-2.2 library is not found. I extracted ext-2.2 to /var/lib/oozie and that resolved this issue.
> Oozie console fix

- hbase/hbase.sh
The current hbase configuration tries to connect the first namenode in Dataproc. It leads to hbase master down when the first namenode  is shutdown or restarted.
To fix this, `hbase.rootDir` should use the value of `fs.defaultFS` in hadoop configuration.
> Initialize HBase for Dataproc HA

- datalab/datalab.sh
Fixes dependency issue. Since dataproc 1.4.X the google cloud storage hadoop filesystem jar file is missing in datalab's classpath.
If you try to access gcs in Datalab via spark (e.g. `spark.read.csv('gs://<bucket>/testfile.csv').show()`) it fails: 
```
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem not found
```
The fix is backwards compatible to previous dataproc versions.
> Datalab: Fix gcs hadoop fs dependency for dataproc 1.4.X

- datalab/datalab.sh
Datalab runs only on master node(s), that's why there no need to install Docker on worker nodes.
> Do not install Docker in Datalab init action on worker nodes

- hbase/README.md
- hbase/hbase.sh
At Commerzbank we have developed a new version of HBase init action that supports Kerberos based authentication. This mode can be changed by passing enable-kerberos and keytab-bucket as cluster metadata during cluster creation process. The script automatically changes the necessary configurations and creates all keytabs necessary for HBase. Please have a look at the init action and the changed documentation.
The provision of HBase with Kerberos and HBase RPC protection enables to securely authenticate and encrypt data transfer from HBase clients (e.g. developed via the HBase Java API) to the cluster. 
Contributors:
@dkoernlein
@PhilippePoth
@kkuemmel
@ThomasStadje
@commerzbank/bdaa
@commerzbank
> HBase Kerberos Configuration and RPC protection

- cloud-sql-proxy/cloud-sql-proxy.sh
Reverts GoogleCloudPlatform/dataproc-initialization-actions#535
Multiple reports of failures:
https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/commit/62e9c743c5cb9a11ed75586947b5013ccb0d88d3
> Revert "Wait until a no-op mysql client invocation succeeds before trying to …"

- cloud-sql-proxy/cloud-sql-proxy.sh
For kerberized clusters, the connect string for beeline needs to include the hive principal
> Make cloud sql proxy init action work on kerberized clusters.

- ganglia/test_ganglia.py
- ganglia/verify_ganglia_running.py
Fixes failure when copying `verify_ganglia_running.py` to cluster VM:
```
ERROR: test_ganglia.mode: STANDARD.version: 1_2.random_prefix: 395b (ganglia.test_ganglia.GangliaTestCase)
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/ganglia/test_ganglia.py", line 55, in test_ganglia
machine_suffix
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/ganglia/test_ganglia.py", line 13, in verify_instance …
```
> Fix Ganglia integration test

- tez/test_tez.py
Failure:
```
ERROR: test_tez_on_image_version_1_3.mode: STANDARD.version: 1_3.random_prefix: y0ng (tez.test_tez.TezTestCase)
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/tez/test_tez.py", line 67, in test_tez_on_image_version_1_3
properties='\'hadoop-env:HADOOP_CLASSPATH=${HADOOP_CLASSPATH}:/etc/tez/conf:/usr/lib/tez/*:/usr/lib/tez/lib/*\'')
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/integrati …
```
> Fix Tez integration test

- oozie/test_oozie.py
Failure:
```
ERROR: test_oozie.mode: HA.version: 1_1.random_prefix: 6l68 (oozie.test_oozie.OozieTestCase)
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/oozie/test_oozie.py", line 43, in test_oozie
machine_suffix
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/oozie/test_oozie.py", line 13, in verify_instance
self.upload_test_file(name)
TypeError: upload_test_file() missing 1 required positional argument: 'name'
```
> Fix Oozie integration test

- drill/drill.sh
- drill/test_drill.py
- drill/validate.sh
Failure:
```
FAIL: test_drill.mode: STANDARD.version: 1_3-deb9.random_prefix: 1217 (drill.test_drill.DrillTestCase)
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/drill/test_drill.py", line 53, in test_drill
"{}-{}".format(self.getClusterName(), target_machine_suffix),
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/drill/test_drill.py", line 19, in verify_instance
self.__run_bash_test_file(name, …
```
> Fix Drill integration test

- gpu/test_install_gpu_driver.py
Disables init action test for 1.1 and 1.2 images.
Failure:
```
FAIL: test_install_gpu_agent.mode: STANDARD.version: 1_1.random_prefix: 3uoo (gpu.test_install_gpu_driver.NvidiaGpuDriverTestCase)
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/gpu/test_install_gpu_driver.py", line 70, in test_install_gpu_agent
scopes='https://www.googleapis.com/auth/monitoring.write'
File …
```
> Fix GPU integration test

- hue/hue.sh
- hue/test_hue.py
- hue/verify_hue_running.py
Failure:
```
FAIL: test_hue.mode: STANDARD.version: 1_0.random_prefix: mbxg (hue.test_hue.HueTestCase)
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/hue/test_hue.py", line 51, in test_hue
machine_suffix
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/hue/test_hue.py", line 20, in verify_instance
self.__run_test_file(name)
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/hue/t …
```
> Fix Hue integration test

- cloud-sql-proxy/test_cloud_sql.py
Fixes failure in test when only GCE zone is set:
```
FAIL: test_cloud_sql_proxy.mode: STANDARD.version: 1_3.random_prefix: nk85 (cloud-sql-proxy.test_cloud_sql.CloudSqlProxyTestCase)
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/cloud-sql-proxy/test_cloud_sql.py", line 33, in setUp
self.DB_NAME, stderr))
AssertionError: 1 != 0 : Failed to create sql instance test-cloud-sql-20190608-213716. Last error: ERROR: (gcloud.sql.instances.create) HTTPError 400: Invalid request: Invalid value for region: global.
```
> Fix Cloud SQL Proxy integration test

- solr/test_solr.py
- solr/verify_solr.py
Failure:
```
FAIL: test_solr.mode: SINGLE.version: 1_2.random_prefix: 5mfe (solr.test_solr.SolrTestCase)
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/solr/test_solr.py", line 48, in test_solr
machine_suffix
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/solr/test_solr.py", line 22, in verify_instance
self.__run_test_script(name)
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-acti …
```
> Fix Solr integration test

- bigdl/README.md
- bigdl/bigdl.sh
The current version of BigDL init script has a very old link to old version of BigZL and doesn't support BigDL with Zoo configurations.
This PR fixes this.
> Intel BigDL 0.7 and Analytics Zoo 0.4 support for dataproc init script

- drill/validate.sh
Prevents Drill test from hanging indefinitely if Drill UI failed to start.
> Fail Drill validate script if Drill UI did not start

- cloudbuild/presubmit.sh
Fixes "TESTS_TO_RUN[@]: unbound variable" error
> Declare TESTS_TO_RUN as a global variable

- rstudio/__init__.py
- rstudio/rstudio.sh
- rstudio/test_rstudio.py
If no password is provided, set the auth-none flag
> Allow disabling RStudio auth by setting blank password

- conda/__init__.py
- conda/install-conda-env.sh
- conda/test_conda.py
- rstudio/__init__.py
- rstudio/test_rstudio.py
This prevents Conda from automatically trying to update itself or Python when installing new packages. These updates can break the Conda installation.
For an example which is currently broken, try telling conda to install Jupyterhub and then interacting with conda on the command line.
```bash
gcloud dataproc clusters create conda-jupyterhub --initialization-actions=gs://dataproc-initialization-actions/conda/bootstrap-conda.sh,gs://dataproc-initialization-actions/conda/install-conda-env.sh --metadata 'CONDA_PACKAGES="jupyterhub"'
gcloud compute ssh conda-jupyterhub-m
conda 
File "/opt/conda/bin/conda", line 7, in <module>
from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```
> Pin Conda and Python versions when setting up Conda environment

- datalab/datalab.sh
> Datalab: add --allow-unauthenticated as a workaround for expired gpg key

- datalab/datalab.sh
- datalab/test_datalab.py
This commit removes the passing of the `--allow-unauthenticated` flag when installing the package `openjdk-8-jre-headless.
That flag was added in #620 to work around an issue in installing the hive and spark-python packages. Since openjdk-8-jre-headless was being installed in the same command, this flag was applied to it as well, even though it was not necessary.
This change locks that back down by splitting the openjdk-8-jre-headless package in a separate command that does not include the `--allow-unauthenticated` flag.
> Require openjdk to be authenticated

- connectors/README.md
- connectors/connectors.sh
Restarting Dataproc Agent using SIGTERM signal could cause cluster node loss.
> Restart Dataproc Agent with SIGKILL signal after connectors update.

- cloudbuild/cloudbuild.yaml
- cloudbuild/presubmit.sh
- cloudbuild/run-presubmit-on-k8s.sh
This avoids running tests for init actions that were changed upstream.
> Rebase PR on the master branch in presubmit

- datalab/datalab.sh
Removed --allow-unauthenticated (workaround for expired gpg key), because the expired gpg key problem is fixed.
> Datalab: remove --allow-unauthenticated

- hbase/hbase.sh
Fixed the way the metadata values `attributes/dataproc-master` and `attributes/dataproc-master-additional` are combined into `MASTER_HOSTNAMES` env var.
The original implementation uses `mapfile` that uses newline a delimiter, which something I don't believe ever worked because the input is a space-separated list.
I changed `mapfile` to regular `read -a`.
> HBase init action fails on HA cluster with `enable-kerberos=true`

- hotfix/README.md
- hotfix/disable-noisy-timeline-server-logs/README.md
- hotfix/disable-noisy-timeline-server-logs/disable-noisy-timeline-server-logs.sh
This commit creates a new "hotfix" top level directory for initialization actions that fix known issues in Dataproc that have not yet been fixed by a new release. This also specifically creates a new initialization action "disable-noisy-timeline-server-logs" that fixes a known issue where the YARN TImeline Server does an excessive amount of logging due to the YARN Resource Manager making bad requests to the Timeline Server REST API. Specifically this initialization action configures a Java util logging configuration file that disables the noisy logger then restarts the timeline server to use the new configuration.
> Add an initialization action for fixing the YARN Timeline Server excessive logging

- datalab/datalab.sh
In Debian 10 host `JAVA_HOME` directory is different from Datalab container's `JAVA_HOME` directory
> Fix Datalab compatibility with Debian 10

- ranger/ranger.sh
Use Python 2 to run Ranger  setup scripts.
> Fix Ranger init action on Dataproc 1.5

- livy/livy.sh
- livy/verify_livy_running.py
The current livy initialization action does not create a livy.conf. Without the conf, livy starts spark with master mode local and ignores all worker nodes. This PR fix the problem by importing the required settings from the spark-defaults.
The changes in the test script are not executed, not sure how to run them.
> Generate default livy.conf from spark-defaults

- connectors/BUILD
- connectors/README.md
- connectors/connectors.sh
- connectors/test_connectors.py
Added functionality to install the [spark-bigquery-connector](https://github.com/GoogleCloudDataproc/spark-bigquery-connector) to the connectors initialization action. Tests updated as well. This supercedes #735.
Added functionality:
- support for metadata `spark-bigquery-connector-version`
- support for metadata `spark-bigquery-connector-url`
> Added support for Spark BigQuery Connector in connectors IA

- starburst-presto/README.md
Reason: Starburst Presto distribution is not used in Presto Component.
> Remove deprecation notice

- starburst-presto/presto.sh
NOTE: If we don't use Java 11
Then we get the following error:
```bash
INFO	main	stderr	ERROR: Future versions of Presto will require Java 11 after March 2020.
You may temporarily continue running on Java 8 by adding the following
JVM config option:
-Dpresto-temporarily-allow-java8=true
```
> Updating presto to v332

- cloud-sql-proxy/cloud-sql-proxy.sh
HiveServer, which runs on an ephemeral cluster and connects to an external Cloud SQL [[official doc](https://cloud.google.com/solutions/using-apache-hive-on-cloud-dataproc)], cannot resolve permanent Hive UDFs that have already been created unless users explicitly execute the Hive `reload function` due to [the limiation of Hive UDFs ](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-Create/Drop/ReloadFunction).
Make the cloud-sql-proxy initialization script to execute the Hive `reload function` so that HiveServer on an ephemeral cluster can resolve permanent Hive UDFs automatically while its creation.
> [cloud-sql-proxy] Execute the Hive "reload function" DDL

- alluxio/test_alluxio.py
- atlas/test_atlas.py
- cloud-sql-proxy/test_cloud_sql_proxy.py
- cloudbuild/presubmit.sh
- conda/test_conda.py
- dr-elephant/test_dr_elephant.py
- drill/test_drill.py
- flink/test_flink.py
- gpu/test_gpu.py
- h2o/test_h2o.py
- hbase/test_hbase.py
- integration_tests/dataproc_test_case.py
- jupyter/test_jupyter.py
- jupyter_sparkmonitor/test_jupyter_sparkmonitor.py
- kafka/test_kafka.py
- knox/test_knox.py
- oozie/test_oozie.py
- presto/test_presto.py
- ranger/test_ranger.py
- rapids/test_rapids.py
- starburst-presto/test_starburst_presto.py
- tony/test_tony.py
This PR improves integration tests efficiency by using cheaper E2 VMs and reduces tests parallelism to prevent hitting external addresses/IPs quota
> Switch integration tests to E2 VMs and reduce parallelism

- flink/flink.sh
Without this, an exception is raised:
>java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
> Flink init action: Set HADOOP_PATH env var to start the yarn session.

- rapids/README.md
- rapids/rapids.sh
- rapids/test_rapids.py
Recent change to init action produced backwards-compatible breaking change requiring Spark 2.x to be explicitly requested. Changes:
- init action can detect Spark version in the environment, no longer requiring passing it in
- default versions for CUDA, CUDF and RAPIDS configured for Spark 2.x and Spark 3.0 (previously passed in at runtime)
- moved spark 2.x property `spark:spark.submit.pyFiles` into init action
- Dask test skipped due to long test time and note of suggestion to use Dataproc 2.0 for this functionality
> [rapids]: improve Spark 2.x compatibility and mix cleanups

- oozie/oozie.sh
Implemented based on [SO answer](https://stackoverflow.com/questions/61233551/how-to-use-gcs-bucket-as-workflow-file-source-for-oozie-in-dataproc/61237392#61237392).
Fixes #798
> Enable use of GCS bucket as workflow file source for Oozie

- gpu/BUILD
- gpu/README.md
- gpu/install_gpu_driver.sh
- gpu/test_gpu.py
- rapids/README.md
- rapids/rapids.sh
- rapids/test_rapids.py
fix documentation for RAPIDS to include cuda 10.1 with Dataproc 1.5, update tests
add cuda 10.1 debian link to GPU init action, update tests
fixes https://github.com/GoogleCloudDataproc/initialization-actions/issues/791
> [rapids][gpu] fix RAPIDS README and GPU default Debian links to support CUDA 10.1

- rapids/rapids.sh
upgrade default rapids to 0.15 for ampere support
> [rapids] Upgrade default RAPIDS version to 0.15 for NVIDIA Ampere GPUs support

- knox/README.md
- knox/knox.sh
I fixed the bucket address in the README.
Rsync is missing in Dataproc 1.5 image. I have added that to the list of software to download for compatibility.
> [knox]: correct bucket name in README and install rsync to fix Debian 10-based images installation

- cloudbuild/run-presubmit-on-k8s.sh
This configuration allows to run 6 test runners/pods on one 8-node k8s node
> Improve test runners bin packing

- jupyter_sparkmonitor/README.md
- jupyter_sparkmonitor/sparkmonitor.sh
- jupyter_sparkmonitor/test_jupyter_sparkmonitor.py
**Rationale:** Jupyter Spark Monitor is not supported for Spark 3.
> Deprecate Jupyter Spark Monitor init action for 2.0+

- gpu/install_gpu_driver.sh
- rapids/rapids.sh
Signed-off-by: Sameer Raheja <sraheja@nvidia.com>
After making the default CUDA version 11.0 for the rapids.sh initialization scripts, we realized that one of our components, RAPIDS Spark XGBoost, is not yet working with 11.0.  We would like to change the default to 10.2 until this component is working with 11.0, which will happen by the end of the year.  
cc: @mengdong @garyshen2008
> [gpu][rapids] Downgrade default CUDA version to 10.2

- rapids/README.md
Removed cuda 10.2 as an option with Spark 2.x (these jars do not exist)
> [rapids] minor readme fix

- integration_tests/dataproc_test_case.py
- rapids/rapids.sh
- rapids/test_rapids.py
There is a dependency conflict with "icu" that conda is unable to solve on it's own. Uninstall it and reinstall with RAPIDS to get correct version and fix the environment.
Also, as we no longer pin PyArrow in 2.0, I removed the logic that was concerned with that.
@mengdong @sameerz FYI
> [rapids] fixing RAPIDS dependency issue

- ganglia/ganglia.sh
according to the https://github.com/ganglia/ganglia-web/issues/303 it is bug of ganglia-web itself
as well same fix was applied by Amazon on EMR
https://aws.amazon.com/premiumsupport/knowledge-center/ganglia-overview-page-blank-emr/
> [ganglia] Fix overview page for Dataproc cluster

- dr-elephant/README.md
Updating README as per issue created at https://github.com/GoogleCloudDataproc/initialization-actions/issues/856 to alert users that Dr. Elephant only works for Spark Versions 2.2.3 and below currently
Fixes #856
> [dr-elephant] Add Supported Spark Version to README

- tony/BUILD
- tony/README.md
- tony/test_tony.py
- tony/tony.sh
Updating TonY and TensorFlow versions.
The version of PyTorch in this init action is also very old. I wasn't able to get this to work with an updated version so I dropped support for it in this init action.  
Also ack:
https://github.com/GoogleCloudDataproc/initialization-actions/issues/833
https://github.com/GoogleCloudDataproc/initialization-actions/issues/834
> [tony] Update TonY and TF versions, remove PyTorch support

- cloud-sql-proxy/cloud-sql-proxy.sh
Context: On newer Dataproc images, we will wait to start hive-server2 until after init actions have been run.
Because of this, we shouldn't try to validate that we can talk to hive-server2 unless it is already running, which will be the case on older Dataproc images.
> [cloud-sql-proxy] Validate that beeline works only if hive-server2 service is already running

- cloudbuild/cloudbuild.yaml
CentOS is not yet supported by init actions.
> Update cloudbuild.yaml to remove CentOS tests

- gpu/install_gpu_driver.sh
- gpu/test_gpu.py
Changes:
- configure YARN NodeManager to use GPUs only if GPUs are attached to the node (fixes 2.0 clusters creation with GPUs attached only to master nodes)
- install NCCL only if cuDNN installed
- code clean up
- run tests for single-node clusters
> [gpu] clean up and fix 2.0 clusters w/ master-only GPUs

- gpu/install_gpu_driver.sh
we were notified init script failed in single node cluster as `resource-types.xml` is missing. 
Also remove nccl to speed up installation. (nccl often use with cudnn for DL workflow)
> [gpu] Add resource-types.xml

- gpu/install_gpu_driver.sh
Fix the content of resource-types.xml. 
It should have "yarn.resource-types" instead of "yarn.nodemanager.resource-plugins" inside.
> [gpu] fix the content of resource-types.xml 

- rapids/BUILD
- rapids/rapids.sh
- rapids/test_rapids.py
Fix a scenario for single-node-cluster where NM is also running on Master.
So we need to restart NM as well if NM is detected on Master.
> [rapids] Fix a scenario for single-node cluster where NM is also running on Master.

- rapids/rapids.sh
Updating RAPIDs to 0.18. This update resolves a dependency conflict that previously required force uninstalling the `icu` dependency. 
Should also resolve https://github.com/GoogleCloudDataproc/initialization-actions/pull/860
> [rapids] Updating RAPIDS to 0.18 and removing force uninstall of 'icu'

- livy/livy.sh
Current instructions do not create home for **livy** user.
It can create problems under some circumstances; for examples when $HOME/.cache/Python-Eggs is being created when dealing with python eggs.
> [livy] Create home dir for livy user

- gpu/install_gpu_driver.sh
- rapids/README.md
- rapids/rapids.sh
Update init script to use RAPIDS Spark v0.4.0
Note that cudf version is 0.18.1 to include a hot fix, this doesn't impact RAPIDS Dask
Also use NVIDIA provided driver as default as it works better with Tesla GPUs that is in GCP
@sameerz @viadea for Viz
Release note could be found here: https://nvidia.github.io/spark-rapids/docs/download.html#release-v040
New features:
```
* Decimal support up to 64 bit, including reading and writing decimal from Parquet (can be enabled by setting spark.rapids.sql.decimalType.enabled to True)
* Ability for users to provide GPU versions of Scala, Java or Hive UDFs
* Shuffle and sort support for struct data types
* array_contains for list operations
* collect_list and average for windowing operations
* Murmur3 hash operation
* Improved performance when reading …
```
> [rapids] Rapids Spark v0.4.0 release

- connectors/connectors.sh
Agent in new releases will not longer be publishing redundant has_run_before flag. We do still need it here for backward compatibility for old images.
Ran only the test_connectors.py which passes.
```
deependrap@deependrap:~/initialization-actions$ bazel test :DataprocInitActionsTestSuite --test_arg=--image_version=2.0 --jobs=25
INFO: Build option --test_arg has changed, discarding analysis cache.
INFO: Analyzed target //connectors:test_connectors (0 packages loaded, 354 targets configured).
INFO: Found 1 test target...
Target //connectors:test_connectors up-to-date:
bazel-bin/connectors/test_connectors
INFO: Elapsed time: 509.349s, Critical Path: 508.95s
INFO: 11 processes: 1 internal, 10 local.
INFO: Build completed successfully, 11 total actions
//connectors:test_connectors …
```
> Check new marker files which will be published in new releases

- gpu/install_gpu_driver.sh
- rapids/rapids.sh
According to https://rapids.ai/start.html, the default rapids conda install should include blazingSQL, also bump up default cuda to cuda 11, cuda 10.x EOL after RAPIDS 0.19.
> install rapids+blazingSQL, bump up to 0.19 release

- jupyter/kernels/install-toree.sh
Fix for https://github.com/GoogleCloudDataproc/initialization-actions/issues/906.
Currently jupyter init action fails as downloading toree artifact 0.2.0-incubating fails. Changing remote url to apache archive.
> Updating upstream url for toree artifact

- gpu/README.md
- gpu/install_gpu_driver.sh
- gpu/test_gpu.py
per https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-versions#centos_images, dataproc 2.0 support centos images, this pull request add gpu libraries installation for centos8 which dataproc 2.0 supports.
BTW, the installation is so slow, I have to use `--initialization-action-timeout=60m`
@bradmiro @sameerz @viadea please review. Thanks
> [GPU]Create CentOS gpu installation init action, clean up os driver install to avoid test failure, pin driver to 460.

- datalab/datalab.sh
Manually added missing GPG keys to fix the apt-get update command.
> [datalab] Fix apt update command execution

- gpu/install_gpu_driver.sh
- rapids/rapids.sh
* Fixing a typo in the GPU init action
* If CUDA 11 is provided, always downloads RAPIDS SPARK jars for 11.0 (until future JARS are released) in the event that say CUDA 11.1 or 11.2 are supplied.
@mengdong please take a look and confirm that the latter is also safe to do. My understanding of CUDA's backwards compatibility is that this should be fine.
> [GPU][RAPIDS] fix typo in GPU and support CUDA 11.2 in RAPIDS

- oozie/oozie.sh
Reverts GoogleCloudDataproc/initialization-actions#935
Reason: integration tests do not pass on CentOS (https://github.com/GoogleCloudDataproc/initialization-actions/pull/937)
> Revert "Supporting Oozie in CentOS"

- dask/README.md
- dask/dask.sh
- dask/test_dask.py
1. Drop support for pre-2.0 images
2. Fix Dask on YARN deployment (see https://github.com/dask/dask-yarn/issues/155 for context)
3. Fix Dask BQ integration
> [dask] Fix Dask init action and drop pre-2.0 images support

- gpu/install_gpu_driver.sh
Use the key package to install cuda repo key.
Following the best practice in https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212772#install-new-cuda-keyring-package-3 .
@medb @mengdong @nvliyuan
> [gpu] Use the key package to install CUDA repo key

- cloudbuild/presubmit.sh
- cloudbuild/run-presubmit-on-k8s.sh
`kubectl logs` command sometimes exits prematurely, so we need to restart and continue logs streaming until container will be terminated.
> Stream presubmit container logs until it container will be terminated

- gpu/README.md
- gpu/test_gpu.py
The following bug is popping up in Dataproc 1.5 when configured with the GPU agent:
```
Jun 28 20:34:51 gpu-agent-1-5-m systemd[1]: gpu-utilization-agent.service: Main process exited, code=exited, st
Jun 28 20:34:51 gpu-agent-1-5-m systemd[1]: gpu-utilization-agent.service: Failed with result 'exit-code'.
Jun 28 20:34:51 gpu-agent-1-5-m systemd[1]: gpu-utilization-agent.service: Service RestartSec=100ms expired, sc
Jun 28 20:34:51 gpu-agent-1-5-m systemd[1]: gpu-utilization-agent.service: Scheduled restart job, restart count
Jun 28 20:34:51 gpu-agent-1-5-m systemd[1]: Stopped GPU Utilization Metric Agent.
Jun 28 20:34:51 gpu-agent-1-5-m systemd[1]: Started GPU Utilization Metric Agent.
Jun 28 20:34:52 gpu-agent-1-5-m bash[15967]: Traceback (most recent call last):
Jun 28 20:34:52 …
```
> Deprecate Dataproc 1.x support for GPU agent

- cloud-sql-proxy/cloud-sql-proxy.sh
- cloud-sql-proxy/pyspark_metastore_test.py
- cloud-sql-proxy/test_cloud_sql_proxy.py
Debian/Ubuntu and Rocky/CentOS have different MySQL config dir and systemd service names.
> [cloud-sql-proxy] Add support for Rocky and CentOS

- rstudio/rstudio.sh
Updates as per https://cran.r-project.org/bin/linux/debian/
> [rstudio] Update CRAN R repo for compatibility with Debian 11

- gpu/install_gpu_driver.sh
We are accidentally prepending 'yarn' to the value here where we instead mean to replace it
> [gpu] Correct error where "yarn" is prepended and doubled

- toree/BUILD
- toree/README.md
- toree/__init__.py
- toree/test_toree.py
- toree/toree.sh
Dataproc clusters currently ship with the Spylon kernel for Scala notebooks.
This new init action enables you to setup Toree as an alternative kernel for Scala
> Add an initialization action for installing the Toree Jupyter kernel

- rstudio/rstudio.sh
Installing Rstudio fails with following on ubuntu 20.04. 
```
Err:12 http://cran.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 51716619E084DAB9
Reading package lists...
W: GPG error: http://cran.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 51716619E084DAB9
E: The repository 'http://cran.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease' is not signed.
```
Adding siging key as per cran documentaiton
> Fix Rstudio installation on Ubuntu 20.04

- cloud-sql-proxy/cloud-sql-proxy.sh
This fix covers the scenario when no hive-metastore-stance is specified, user may provide additional-cloud-sql-instances or not provide any instance at all, in such case we first check if additional-cloud-sql-instance is provided, if not, default to mysql for backward compatibility.
> Do not fail when no metastore instances is set

- gpu/README.md
- gpu/install_gpu_driver.sh
- gpu/test_gpu.py
* capture distribution from /etc/os-release for use in logging
* create a matrix of supported nvidia kernel driver, cuda, cudnn and nccl versions
* simplify default cuda version specification
* exit early on cuda versions known to be unsupported
* remove unused dataproc node role variable
* allow user to specify gpu-driver-version from metadata argument
* simplify rocky nccl version delta on cuda 11.2
* provide reasonable default cudnn version
* include current kernel version in kernel-devel package name
* use mkdir -p to ensure idempotency
* add support for CUDA > 11.5 on Debian
> [gpu] Updated GPU driver install script

- spark-rapids/spark-rapids.sh
remove unnecessary steps to config yarn in spark-rapids init script
> [rapids]remove unnecessary steps to config yarn

- oozie/oozie.sh
With earlier logic, it was always printing node count as (actual node count  - 1 ).
Example for earlier logic:
```
kuldeepkk@cluster-oozie-init-testing-m-0:~$ /usr/share/google/get_metadata_value attributes/dataproc-master-additional|sed 's/,/\n/g'|wc -l
1
```
```
kuldeepkk@cluster-oozie-init-testing-m-0:~$ /usr/share/google/get_metadata_value attributes/dataproc-master-additional
cluster-oozie-init-testing-m-1,cluster-oozie-init-testing-m-2kuldeepkk@cluster-oozie-init-testing-m-0:~$
```
Note that there is no '\n' after the results hence line count is always (expected line count - 1)
After changing variable:
```
kuldeepkk@cluster-oozie-init-testing-m-0:~$ additional_nodes=$(/usr/share/google/get_metadata_value attributes/dataproc-master-additional) …
```
> Added an extra variable to reflect the correct node count

- spark-rapids/spark-rapids.sh
This pr is to fix this [issue](https://github.com/NVIDIA/spark-rapids/issues/8149).
Add a cleaner error message for supported cuda versions.
And fix a error for ubuntu20-img2.1 version.
> [rapids]add a cleaner error message for supported cuda versions

- spark-rapids/spark-rapids.sh
This PR is to patch spark-rapids.sh file. It fixes the build failure error due to "DATAPROC_IMAGE_VERSION: unbound variable" while creating custom image. 
signed-off-by: suraj.ara16@gmail.com
> fix missing DATAPROC_IMAGE_VERSION

- connectors/connectors.sh
- connectors/test_connectors.py
* In 2.1 images, environment variable is DATAPROC_IMAGE_VERSION
* added functions to compare versions
* When image version is >= 2.1, use scala v2.13
> Fixes to enable connectors on 2.1 images

- oozie/README.md
- oozie/oozie.sh
- oozie/test_oozie.py
- oozie/validate.sh
* detect version of Dataproc image
* clean up find -delete command
* use non-deprecated version of dfsadmin
* copy dataproc version specific curator jars to /usr/lib/oozie/lib
* update Copyright for oozie/oozie.sh
* Install fluentd configuration
* Accepting many more configuration options
* Setting default MySQL credentials
* retries are delayed after the first
* configure more default properties
* improved support for rocky8 images
* handling some race conditions
* pre-populate sharelib
* proactive log4j 1.2 mitigations
> [oozie] Enable oozie on 2.1 images

- BUILD
- otel/BUILD
- otel/otel.sh
- otel/test_otel.py
- Original PR: #1072 
- Added integration test against OpenTelemetry init action
- Added support for rocky-8
PR credits: @shambhavirai16
Original author could not continue contribution.
> Added OpenTelemetry Initialization action for Dataproc clusters (along with integration tests)

- spark-rapids/spark-rapids.sh
This PR updates spark-rapids.sh init script with the latest 23.08.1 (to-date) rapids-4-spark version.
signed-off-by: Suraj Aralihalli <suraj.ara16@gmail.com>
> update spark rapids version to 23.08.1

- livy/README.md
- livy/livy.sh
Latest release of livy breaks the binary distributions into those linked against scala 2.11 and those against 2.12
This update takes this change into account
This change also installs to Dataproc 2.1+ images
> [livy] Update livy init action to use latest release

- bigtable/bigtable.sh
- bigtable/test_bigtable.py
* updated copyright date
* set variables distribution and DATAPROC_IMAGE_VERSION
* updated BIGTABLE_HBASE_CLIENT_1X_VERSION to latest, '1.29.2'
* corrected and tested BIGTABLE_HBASE_CLIENT_2X_* variables
* specifying HBASE_VERSION="2.3.6"
* ensured that BIGTABLE_INSTANCE metadata variable is supplied
* simplified call to install_bigtable_client to remove requirement for arguments
* Create "${HBASE_HOME}/conf/hbase-site.xml" if not exist
* corrected hbase.client.registry.impl to org.apache.hadoop.hbase.client.BigtableConnectionsRegistry
* renamed DATAPROC_VERSION variable to DATAPROC_IMAGE_VERSION
* moved hbase installation logic out of function main into a new function install_hbase
* using hbase apt-get logic only for dataproc versions < 2.1
* developed new hbase installation logic for …
> [bigtable] Update to work with 2.0+

- livy/livy.sh
Scala variance not available before 0.8.0
> [livy] do not inject scala version into LIVY_PKG_NAME when LIVY_VERSION < 0.8

- spark-rapids/spark-rapids.sh
- spark-rapids/test_spark_rapids.py
This PR addresses the following issues:
1. **Supported Linux Distros:**
- Continued support for three Linux distro families: Debian 10, Debian 11, Ubuntu 20, Ubuntu 18 and Rocky 8
- Adds support for Ubuntu 22, Rocky 9 (for future Dataproc releases)
2. **Drops Support for Spark 2.x**
3. **Default Driver Version Update:**
- Previous default driver version 495.29.05 coupled with CUDA 11.5.
- L4 Gpus require a minimum of 525 and failed with existing init script
- New default driver version: 535 (535.104.05) for all three operating systems allows support for L4 Gpus.
- Cuda 12.1.1 - Driver v530.30.02 is used for Ubuntu 18 only
4. **Improved CUDA Driver Installation:**
- Transitioned from run files to package manager for NVIDIA driver installation on Ubuntu and Debian
- Prevents driver failures …
> [spark-rapids] Fix/Update Driver Installation method for Debian, Ubuntu, and Rocky Linux

- spark-rapids/mig.sh
This PR updates the MIG script to use the latest driver installation method and also addresses the following issues
1. **Supported Linux Distros:**
- Continued support for three Linux distro families: Debian 10, Debian 11, Ubuntu 18, Ubuntu 20 and Rocky 8
- Adds support for Ubuntu 22, Rocky 9 (for future Dataproc releases)
2. **Default Driver Version Update:**
- Previous default driver version 495.29.05 coupled with CUDA 11.5.
- L4 Gpus require a minimum of 525 and failed with existing init script
- New default driver version: 535 (535.104.05) for all three operating systems allows support for L4 Gpus.
- Cuda 12.1.1 - Driver v530.30.02 is used for Ubuntu 18 only
3. **Improved CUDA Driver Installation:**
- Transitioned from run files to package manager for NVIDIA driver installation on …
> [spark-rapids] Update MIG script

- zeppelin/zeppelin.sh
This will not make zeppelin work on 2.1 image, instead users should use  --optional-components=ZEPPELIN
> [zeppelin] corrected DATAPROC_VERSION to DATAPROC_IMAGE_VERSION

- spark-rapids/spark-rapids.sh
This PR 
1. Updates spark-rapids.sh init script with the latest 23.10.0 (to-date) rapids-4-spark version.
2. Fixes issue #1109
3. Installs java ca certificates for deb 10 ahead of driver installation.  
> Update spark rapids version to 23.10.0

- gpu/README.md
This argument will allow kernel modules built from source to load into Dataproc kernels.
> [gpu] Added recommendation to use --no-shielded-secure-boot

- BUILD
- alluxio/test_alluxio.py
- atlas/test_atlas.py
- bigtable/test_bigtable.py
- cloud-sql-proxy/hivetest.hive
- cloud-sql-proxy/test_cloud_sql_proxy.py
- dask/dask.sh
- drill/test_drill.py
- ganglia/test_ganglia.py
- gpu/test_gpu.py
- h2o/h2o.sh
- horovod/horovod.sh
- horovod/test_horovod.py
- integration_tests/dataproc_test_case.py
- mlvm/mlvm.sh
- ranger/ranger.sh
- ranger/test_ranger.py
- rapids/test_rapids.py
- solr/test_solr.py
- solr/verify_solr.py
- sqoop/BUILD
- sqoop/sqoop_sql.sh
- sqoop/test_sqoop.py
- starburst-presto/test_starburst_presto.py
- tony/test_tony.py
While running the presubmits, there are many components for those presubmit failures are breaking. The components are as follows:
1. bigtable
2. ganglia
3. h2o
4. horovod
5. gpu
6. tony
7. mlvm
8. hive llap
9. sqoop
10. cloudsql proxy
There might be other components as well, but to mention these are the components which require immediate attention.
> fixing presubmit failures for the respected components

- integration_tests/dataproc_test_case.py
- kafka/BUILD
- kafka/README.md
- kafka/kafka.sh
- kafka/test_kafka.py
- kafka/verify_kafka_running.py
For Kafka, adding the tests for submission of jobs and verifying instances to increase the coverage for overall scope. The test now runs kafka jobs with cruise-control and kafka-manager. Also, adding the test for cruise-control and kafka-manager instance verification.
> Improving the init action test for Kafka

- livy/livy.sh
- livy/test_livy.py
Expanding the livy test to manipulate the metadata fields and submit the pyspark job with livy up and running verification script.
> Expanding the livy test

- oozie/BUILD
- oozie/oozie.sh
- oozie/test_oozie.py
- oozie/verify_oozie_running.py
For Oozie test, creating new test cases to submit the pyspark jobs for multiple components. The components covered are as follows:
1. distcp
2. hive
3. map-reduce
4. shell
5. pig
6. spark
7. sqoop
> Extending the Oozie test to submit the jobs

- oozie/oozie.sh
> [oozie] Using $(hostname -s) rather than ${HOSTNAME}

- hue/hue.sh
> [hue] Using $(hostname -s) vs ${HOSTNAME}

- starburst-presto/presto.sh
> [starburst-presto] Use $(hostname -s) vs ${HOSTNAME}

- ganglia/ganglia.sh
> [ganglia] Using $(hostname -s) vs ${HOSTNAME}

- hbase/hbase.sh
> [hbase] Using $(hostname -s) vs ${HOSTNAME}

- presto/presto.sh
> [presto] Using $(hostname -s) rather than ${HOSTNAME}

- cloudbuild/cloudbuild.yaml
- connectors/connectors.sh
- dask/dask.sh
- hue/test_hue.py
- kafka/test_kafka.py
- livy/test_livy.py
- spark-rapids/test_spark_rapids.py
Adding the configuration for running the init action tests for 2.2 dataproc images as well and alongside making minor changes in accordance to support the init action for 2.2 images.
> Adding configuration in cloud build to run the tests for 2.2 Dataproc Images

- spark-rapids/spark-rapids.sh
This PR
Updates spark-rapids.sh init script with the latest `24.02.0` (to-date) rapids-4-spark version and adds support for
- 2.2-ubuntu22
- 2.2-debian12
> Update spark rapids version to 24.02.0

- gpu/install_gpu_driver.sh
https://github.com/GoogleCloudDataproc/initialization-actions/issues/1157
> Remove backports for releases older than oldstable

- rstudio/rstudio.sh
Based on https://stackoverflow.com/questions/67251078/gpg-keyserver-send-failed-no-keyserver-available-when-sending-to-hkp-pool
> Issue #1175: [rstudio] use keyserver.ubuntu.com

- spark-rapids/spark-rapids.sh
- spark-rapids/test_spark_rapids.py
This PR updates 
1. spark-rapids.sh init script with the latest 24.02.0 (to-date) rapids-4-spark version.
2. Changes default driver version to `550.54.15` and cuda `12.4.1`
3. Uses `apt-get --allow-releaseinfo-change update` to unblock downstream applications until dataproc platform fixes `apt-get update` issues in Debian 10 and Ubuntu linux distros. 
> [spark-rapids] Update spark rapids version to 24.04.0

- spark-rapids/spark-rapids.sh
This PR updates
- Fixes rocky 8,9 driver install steps
- Update RAPIDS Accelerator to 24.06.0
> [spark-rapids] Update spark rapids version to 24.06.0

- integration_tests/dataproc_test_case.py
- rstudio/rstudio.sh
**libdeflate-dev** and **libdeflate0** are removed from the ubuntu library being used as source. 
- Make a temporary directory
- Download the archived version for both mentioned packages in the temp directory
- Using **dpkg** install both the packages and call the function only when the **OS** is **ubuntu** and the **image version** is **2.0**
> [RStudio] fixing the test failure for 2.0 ubuntu images.

- gpu/install_gpu_driver.sh
* wrapped signing code in conditional that checks for private key
* replaced tabs with spaces
* made use of get_metadata_attribute more frequently
* using default value of "" unless otherwise supplied
* using CUDA subversion of 12.4.1
* building source in /opt/install-nvidia-driver
> [gpu] do not require signing metadata

- dask/dask.sh
We re-combined the mamba and conda commands since the python versions resolve on these dask releases.
manual tests performed:
* 2.0-debian10 without metadata dask-runtime set
* 2.0-debian10 with metadata dask-runtime set to standard
* 2.1-debian11 with metadata dask-runtime set to standard
* 2.1-debian11 with metadata dask-runtime set to yarn
* 2.2-debian12 without metadata dask-runtime set
* 2.1-debian12 with metadata dask-runtime set to standard
> [dask] updated dask version to 2022.3 on 2.0 and 2.1, 2024.06 on 2.2

- bigtable/bigtable.sh
- bigtable/test_bigtable.py
Thanks to @dilipgodhia for the patch
tests done were manually, and only exercised the variable changed:
```
SCH_REPO="https://repo.hortonworks.com/content/repositories/releases/com/hortonworks"
SHC_VERSION='1.1.1-2.1-s_2.11'
SHC_JAR="shc-core-${SHC_VERSION}.jar"
SHC_EXAMPLES_JAR="shc-examples-${SHC_VERSION}.jar"
SHC_URL="${SCH_REPO}/shc-core/${SHC_VERSION}/${SHC_JAR}"
SHC_EXAMPLES_URL="${SCH_REPO}/shc-examples/${SHC_VERSION}/${SHC_EXAMPLES_JAR}"
cjac@cjac:~/src/github/cjac/initialization-actions$ wget "${SHC_EXAMPLES_URL}" ; echo $?
--2024-07-08 09:54:06--  https://repo.hortonworks.com/content/repositories/releases/com/hortonworks/shc-examples/1.1.1-2.1-s_2.11/shc-examples-1.1.1-2.1-s_2.11.jar
Resolving repo.hortonworks.com (repo.hortonworks.com)... 54.149.82.252, 35.164.245.218, …
```
> [bigtable] using modern url for shc-core and shc-examples jar packages

- gpu/install_gpu_driver.sh
1. install_gpu_driver.sh init script fails with the following error in rocky 2.0 and 2.1 images:
```
++ dnf -y -q update
Error: 
Problem: The operation would result in removing the following protected packages: systemd
```
We should exclude systemd from dnf update.
2. In 2.0 rocky, the available version of kernel-devel is `4.18.0-513.9.1.el8_9.x86_64` which does not match the running kernel version `4.18.0-477.27.1.el8_8.x86_64`.
```
++ dnf -y -q install kernel-devel-4.18.0-477.27.1.el8_8.x86_64
Error: Unable to find a match: kernel-devel-4.18.0-477.27.1.el8_8.x86_64
```
There should be a condition to check if the kernel needs to be upgraded. 
`upgrade_kernel` method has been taken from https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/spark-rapids/spark-rapids.sh#L …
> Fix install_gpu_driver.sh failures in rocky 2.0 and 2.1 images

- rapids/rapids.sh
- rapids/test_rapids.py
* adding functions to check running environment OS
* set rapids version to 23.12
* set cuda version to 11.8
* remove cudf variables - they are unused
* set xgboost version to 2.0.3
* created variable to store scala version for future move from 2.12 to 2.13
* setting python_ver by operating system
> [rapids] bringing action up to date

- hue/README.md
- hue/hue.sh
modified:   hue/README.md
* line-wrapped and clarified important note
modified:   hue/hue.sh
* added functions os_id, is_debian, is_debian10, is_ubuntu
* only adding buster-backports to sources.list for debian10
* update_repo now uses is_debian || is_ubuntu rather than checking for apt-get in path
* setting DEBIAN_FRONTEND=noninteractive before installation of hue ; mysql-community-server had an important message that it was prompting the user to answer on a non-interactive console, halting tests.
* added note that we may need to specify this option with debconf
* jettisoned my function remove_old_backports with preference for Prince's much better replace_backports_repo
* using slightly different logic to determine whether we replace the backports repo
> [hue] update action for July 2024

- bigtable/bigtable.sh
* using better implementation of debian backports repo update
* fetching shc jar from a local cache rather than from cloudera's deprecated repos
> [bigtable] retry failed hbase download attempts

- spark-rapids/spark-rapids.sh
This PR uses `apt-mark hold` to prevent auto upgrades for Nvidia packages.
signed-off-by: Suraj Aralihalli <suraj.ara16@gmail.com>
> [spark-rapids] Prevent automatic updates for Nvidia packages

- dask/dask.sh
- dask/test_dask.py
- dask/verify_dask_standalone.py
- dask/verify_dask_yarn.py
Updated to work with modern packages
dask.sh:
* removed most os condition tests ; this action is generally OS agnostic
* using the specific conda environment rather than the "default"
* declaring variables where they are used
* broke systemd units into scheduler and worker
* * only starting scheduler on primary master
* * only starting worker on master if dask-worker-on-master is not set to false
* updated knox xml to reference master node instead of localhost
* since dask-yarn only works with older libs, we are much more specific about the mamba/conda install packages
test_dask.py:
* removed rocky test inhibitions
* changed test machine type from e2-standard-2 to n1-standard-16
* self.verify_dask_standalone now takes an argument pointing to the master node
* using correct conda …
> [dask] Updated to work with modern environments

- cloudbuild/cloudbuild.yaml
- cloudbuild/presubmit.sh
- gpu/install_gpu_driver.sh
* using CUDA 12.4 by default for all use cases
* fetch nvidia kernel code from tarball instead of git clone
> [gpu] non-spark rapids runtime should also use CUDA 12.4

- gpu/install_gpu_driver.sh
- gpu/test_gpu.py
write trust keys to files under /usr/share/keyrings/
encode that path as signed-by into sources.list file for each repository
rename trusted.gpg
full-update to latest packages
force install of held packages to clear error
> [gpu] workaround for broken apt trust database

- knox/knox.sh
The knox.sh script has been updated to ensure compatibility across various Dataproc image versions. Here's a summary of the changes:
2.0.X-debian10:
Addressed an issue where the script failed for image versions less than or equal to 2.0.102-debian10 due to original keys had expired at https://keyserver.ubuntu.com.
Note: Cluster creation with these versions requires the cloud-platform scope.
2.1.X-debian11: The script functioned correctly with all 2.1.X-debian11 image versions.
2.2.x-debian12: Script was not working for 2.2 images . Resolved a problem caused by the hostname returning an FQDN in 2.2.x-debian12 images.
Testing:
Thorough testing was conducted with various cluster naming conventions (e.g., proxy-cluster, proxy-cluster-x, proxy-cluster-x-v) and across all supported image …
> redirect backports repo on oldoldstable

- gpu/install_gpu_driver.sh
Updates for Rocky, plus updates to allow the script to be run by the custom image generator
* reduce log noise a little
* Only unhold systemd on debian12
* encode get_metadata_value logic inline so this script works where `/usr/share/google/get_metadata_value` is not installed (custom-images)
* clean up argument passing to `execute_with_retries`
* allow access to DKMS keys for the duration of the install process instead of just during driver signing
* On Rocky, try to build drivers using DKMS with a fallback of installing pre-built binaries
* Do not install driver aliases on rocky
* remove extra `modprobe -r`
* in `configure_yarn`, skip update if `${HADOOP_CONF_DIR}` does not exist
* only `chown yarn:yarn` for directory list if directory list is not empty (including existing as a single …
> [gpu] updates as result of rocky tests and running script with custom image generator

- dask/dask.sh
replace execution of /usr/share/google/get_metadata_value attributes/$1
with calls to get_metadata_attribute $1
using `/opt/conda/miniconda3/bin/mamba` directly since the `default` symlink has not yet been created during pre-init
> [dask] now safe to execute as pre-init customization script

- horovod/horovod.sh
- horovod/test_horovod.py
- Adding the correct versions for the framework versions as they will be varying on the Dataproc version being used. 
- Ignoring the tests run for Dataproc versions 2.1 and 2.2 because it is not supported with the current framework versions being suggested and downgrading doesn't allow the frameworks to be installed.
> Horovod test fix 

- gpu/Dockerfile
- gpu/README.md
- gpu/bazel.screenrc
- gpu/env.json.sample
- gpu/install_gpu_driver.sh
- gpu/manual-test-runner.sh
- gpu/run-bazel-tests.sh
- gpu/test_gpu.py
* Capturing disk usage statistics to reduce excessive disk space
* created exit handler to clean up environment on completion or failure
* created prepare function to prepare for the installation
* when sufficient memory is available, configure a ramdisk
* reduce noise by turning off -x in utility functions
* added descriptive comments before the obscurely coded compare_versions_lte and compare_versions_lt functions
* removed some intermediate driver versions
* added cuda url for 12.6
* execute_with_retries now logs on failure, captures runtime and cleans before installing on debian
* saving OS installation and NV .run files and their temp files to ramdisk
* piping source .xz file directly xz instead of saving to disk first
* new utility function "is_debuntu" checks for the frequently …
> [gpu] performance and functionality improvements

- cloudbuild/Dockerfile
* now using environment variables more
* using gpg --import instead of gpg --dearmor
* must set default bazel using update-alternatives or bazel is not in PATH, only bazel-7.4.0
* Although this could possibly be solved by replacing all calls to bazel in our code with bazel-7.4.0 this does not hold true for others' code which does not know to change the abi
> [bazel] updated to allow pinning of bazel version

- spark-rapids/mig.sh
Resolves #1259
This PR updates the MIG script to align the driver installation steps with those in `spark-rapids.sh`.
> [gpu][spark-rapids] Fix MIG script

- BUILD
- hive-lineage/README.md
- hive-lineage/__init__.py
- hive-lineage/hive-lineage.sh
- hive-lineage/hivetest.hive
- hive-lineage/test_hive_lineage.py
This initialization action configures Google Cloud Dataproc to enable lineage for Hive jobs.
Lineage for Hive is currently not supported, and is not configurable through cluster properties as of now. We are going preview with this feature through initialization actions.
> Add script and readme for hive lineage

- cloudbuild/presubmit.sh
- gpu/Dockerfile
- gpu/install_gpu_driver.sh
- gpu/manual-test-runner.sh
- gpu/run-bazel-tests.sh
- gpu/test_gpu.py
- integration_tests/dataproc_test_case.py
[gpu] strict driver and cuda version assignment
This change re-applies the changes from PR #1275 and fixes some issues users were experiencing when specifying parameters.
gpu/install_gpu_driver.sh
* updated supported versions
* moved all code into functions, which are called at the footer of
the installer
* install cuda and driver exclusively from run files
* extract cuda and driver version from urls if supplied
* support supplying cuda version as x.y.z instead of just x.y
* build nccl from source
* poll dpkg lock status for up to 60 seconds
* cache build artifacts from kernel driver and nccl
* use consistent arguments to curl
* create is_complete and mark_complete functions to allow re-running
* Tested more CUDA minor versions
* Printing warnings when combination provided is known to …
> Roll forward PR #1275 with fixes

- hive-lineage/hive-lineage.sh
- hive-lineage/test_hive_lineage.py
This change appends hive confwhitelist in hive-lineage.sh to allow users to set custom hive openlineage properties at runtime.
In the previous version of the script, workloads were failing for kerberos-enabled clusters when setting `hive.openlineage.namespace` in job properties. This change fixes the issue.
> [hive-lineage] Update hive-lineage.sh

- gpu/install_gpu_driver.sh
- gpu/test_gpu.py
* only pause for completion in github tests, not internal tests
* better timestamp extraction logic
* write directly to trust keychain with `gpg --recv-keys`
* fix string match code for GPU identification
* [disabling rocky9 builds due to out of date base dataproc image](https://github.com/GoogleCloudDataproc/initialization-actions/pull/1317/commits/b5b5c46e0e85403c31157d50b5fad7d9e4ed3fbe)
> [gpu] exercise tests against internal suite

- spark-rapids/spark-rapids.sh
Resolves #1321 
- Added `unhold_nvidia_packages` function to allow upgrades of NVIDIA packages.
- Updated `hold_nvidia_packages` function to suppress output during execution.
- Integrated `unhold_nvidia_packages` call in the `install_nvidia_gpu_driver` function to ensure packages can be upgraded as needed.
> Enhance NVIDIA package management in spark-rapids.sh

- spark-rapids/spark-rapids.sh
This pr is to update the spark-rapids jar version after plugin release
> update the default spark-rapids version to 2506
