apache-zeppelin/README.MD
Added additional details and clarifications to Apache Zeppelin readme file. Ultimate goal is to have README files follow an approximately similar format.
=> Clarifications and additions to Apache Zeppelin README

presto/README.MD, presto/presto.sh
Addition of presto initialization action.
=> Adding Presto init action

conda/bootstrap-conda.sh
=> BUG: Remove sourcing of .bashrc

apache-zeppelin/zeppelin.sh
=> #27 fix race condition in Zeppelin initialization action

apache-zeppelin/zeppelin.sh
Closes https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/issues/35
=> Updated zeppelin.sh to use apt-get install

zookeeper/zookeeper.sh
Related to https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/issues/35
=> Modified zookeeper.sh to install Zookeeper from repo.

README.md, flink/README.md, flink/flink.sh
(fix for broken GitHub stuffs this morning; adding new Flink init action)
=> Adding Flink initialization action

README.md, datalab/README.md, datalab/datalab.sh, flink/flink.sh, ipython-notebook/ipython.sh, kafka/kafka.sh, stackdriver/stackdriver.sh, tez/tez.sh, zeppelin/README.MD, zeppelin/zeppelin.sh, zookeeper/zookeeper.sh
=> Add Google Cloud Datalab init action.

cloud-sql-proxy/pyspark_metastore_test.py
Fixed DataFrame filter to make the job pass
=> Fixed issue in Cloud SQL pyspark test job

flink/README.md, flink/flink.sh
Reverts GoogleCloudPlatform/dataproc-initialization-actions#118
=> Revert "Disable long-running flink yarn session by default."

jupyter/README.MD
Document JUPYTER_AUTH_TOKEN metadata property referenced in #81.
=> Update documentation on Jupyter auth

presto/presto.sh
In /etc/spark/conf/spark-defaults.conf, some settings use "=" and other use
whitespace to define Spark's settings. With the Dataproc image
version upgrade, one of them changed to use whitespace and that
prevented this script from working properly. To add a bit of robustness
to the script, use regex to make sure this works both "=" and
whitespace. In addition, if spark.yarn.executor.memoryOverhead is not
defined, it uses the default Spark property value.
=> Use sed instead of cut to extract Spark settings

oozie/oozie.sh
=> oozie: ensure resources is restarted to pick up the oozie configuration

cloud-sql-proxy/README.MD
Fixes #153 
CC @roscoejp, @spark2ignite
=> Add note to enable Google Cloud SQL API

zeppelin/README.MD, zeppelin/zeppelin.sh
=> Install matplotlib for Zeppelin

kafka/kafka.sh
…to follow https://google.github.io/styleguide/shell.xml. 
As described in https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/issues/187
=> Kafka script updated

stackdriver/stackdriver.sh
Per official instructions at https://cloud.google.com/monitoring/agent/install-agent#linux-install.
@dhrupadb FYI.
=> Update stackdriver.sh with the latest commands

hive-hcatalog/hive-hcatalog.sh
Refactored items:
- update apt-get
- check if package was installed, otherwise provide custom log
(part of #200 )
=> refactor hive-hcatalog init-action to follow shell script guidelines

zeppelin/zeppelin.sh
This reverts commit 0e82573e84de0d6b10ee2eefbba76353ff99441c.
=> Revert "Adjust Zeppelin init action to conform the guidelines. (#191)"

datalab/datalab.sh
This PR is related to #200. 
Changed items:
- moved constants to top of the file
- add err function and check return values when applicable
- copy only files needed by `Dockerfile`, not all of them in directory
following issues are identified, but left as-is as changing them to strictly follow guidelines will degrade readability
- `set -u` flag can't be set as script uses standard environment variables that are not declared within the script
- Usages `sed` could probably be replaced by bash equivalent but it's more readable as is 
- Using symlinks instead of `cp` is not possible, as files must exists in the same directory as `Dockerfile`. Symlinks are not followed.
- there is no systemd configuration, but `docker run --restart=always` seems good enough
- `main` function doesn't seem to be …
=> refactor datalab init-action to follow shell script guidelines

oozie/oozie.sh
This PR is related to #200.
Tested with map-reduce app on Single Node and Standard configuration - on HA mode cannot initialize cluster. I've mentioned about it in issue #211 and behavior is paralleled with script before changes.
- Functions extraction
- Error handling
- Replaced copy operations with symbolic links
- Fixed spaces
=> Oozie review changes

README.md, presto/README.MD, presto/presto.sh
=> Fix Single-Node and HA configurations for Presto

ganglia/ganglia.sh
Ganglia changes to make script consistent with shell style guide. 
Tested on 1.2.27 image-version. 
Did not observe behavior from issue #146 . Web interface is displayed using path : localhost/ganglia/.
=> Ganglia review changes

tez/tez.sh
This fixes issue described in #199 .
=> Fixing Tez init action issues with copying tez jars to hdfs in HA mode.

hue/hue.sh
Changes:
– error handling
– variables moved to locals
– bdconfig instead of sed
– main function added
=> Made Hue script consistent with shell style guide requirements

jupyter/jupyter.sh
Fix forward for #247 , which reverted #237
=> Install matplotlib for Jupyter using `conda`

cloud-sql-proxy/cloud-sql-proxy.sh
See more details here: https://stackoverflow.com/a/44938499
=> [Cloud SQL Proxy] Fix metadata key for additional instances

tez/README.MD, tez/tez.sh
Changes Tez UI from http://clustername-m:9999 to
http://clustername-m:8188/tez.
=> [Breaking change] Run Tez UI in App Timeline Server

cloud-sql-proxy/README.MD, cloud-sql-proxy/cloud-sql-proxy.sh
=> [Cloud SQL Proxy] Protect passwords with KMS

oozie/oozie.sh
This commit solve issue from #211.
=> Run Oozie in High Availability Mode

oozie/README.MD
1) Add Cloud Composer as an alternative to Apache Oozie
2) Clarify the "Testing Oozie" section
=> Improve Oozie README

presto/presto.sh
Also, add missing configuration properties to avoid crash looping of presto
server.
=> Upgrade presto to use latest released version.

ganglia/ganglia.sh
Fixes https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/issues/284
External issue with the fix:
https://www.mail-archive.com/ganglia-general@lists.sourceforge.net/msg09253.html
=> Fix issue when Ganglia metrics don't show up.

conda/bootstrap-conda.sh
=> Set CLOUDSDK_PYTHON to system python

conda/README.MD, conda/bootstrap-conda.sh
=> Pin miniconda version to avoid breaking changes

jupyter/jupyter.sh
=> Install jupyter on all nodes to ensure consistent python version

ganglia/ganglia.sh
Fixes https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/issues/316
=> Fix Ganglia configuration of worker nodes

ganglia/ganglia.sh
Fixes https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/issues/316
=> Configure Ganglia nodes to send metrics to host

connectors/connectors.sh
Fixes https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/issues/337
=> Fix AccessDeniedException in connectors init action

docker/docker.sh
It is reasonable to expect that Docker users on Dataproc will want it
to automatically integrate with the Google Container Registry.  This
change configures Docker to use GCR as part of the initialization
action.
This change is also useful for Beam users who are building
their own container images and storing them on GCR.
=> Configure Docker to use GCR during initialization

oozie/oozie.sh
This PR solves issue from #326. 
I moved all hadoop related stuff inside if block which is executed only on nodes that are not marked as additional ones.
=> Fix for oozie intialization on clusters with many worker nodes

secure/README.md, secure/secure.sh
Kerberizing clusters in HA mode + some minor code clean up.
=> Kerberos in HA

secure/README.md, secure/secure.sh
add back accidentally deleted 'mapreduce.ssl.enabled:true' property
=> add back accidentally deleted 'mapreduce.ssl.enabled:true' property

secure/secure.sh
fix new nodes launched from update cluster request could not register with RM
The dataproc agent perform initialization in different orders when creating vs updating a cluster. Restart nodemanger and datanode should only happen in certain conditions, otherwise initialization will fail.
=> fix new nodes launched from update cluster request could not register with RM

cloud-sql-proxy/cloud-sql-proxy.sh
=> Only check 3306 if using cloud sql for metastore

jupyter/jupyter.sh
=> Allow adding multiple Conda channels in Jupyter init action

jupyter/jupyter.sh
=> Install matplotlib first to prevent dependencies conflict

bigtable/__init__.py, bigtable/run_hbase_commands.py, bigtable/test_bigtable.py, integration_tests/dataproc_test_case.py
To run the test just use command:
python -m unittest bigtable.test_bigtable
=> Integration test for Bigtable init action.

ganglia/test_ganglia.py, ganglia/verify_ganglia_running.py
These scripts can be used for testing Ganglia init action on single, standard and ha configurations.
=> Ganglia integration tests

kafka/__init__.py, kafka/test_kafka.py, kafka/validate.sh
Tests can be run using command:
python -m unittest kafka.test_kafka
=> Added integration tests for Apache Kafka.

presto/presto.sh
@functicons this is the init-action change I wanted to add as part of #376. PTAL
=> wait for Presto to be fully working before completing init-action

presto/__init__.py, presto/presto.sh, presto/test_presto.py
=> added integration test for Presto

tony/README.md, tony/test_tony.py, tony/tony.sh, tony/validate.sh
Add support to install TonY automatically.
https://github.com/linkedin/TonY/tree/master/tony-examples/tony-in-gcp
=> Add LinkedIn TonY support to Dataproc

tony/README.md
Correct wording
Remove inaccurate statement in regards GPU
=> Fix TonY README.md

flink/test_flink.py, flink/validate.sh
These scripts can be used for testing Flink init action on single, standard and ha configurations.
=> Flink integration tests

stackdriver/README.md
=> Adds deprecation note to stackdriver initialization action

drill/test_drill.py, drill/validate.sh
These scripts can be used for testing Drill init action on single, standard and ha configurations.
=> Drill integration tests

jupyter/kernels/install-toree.sh
This PR fix temporarily the PR #293.
=> chaging toree repository url

rstudio/README.MD, rstudio/rstudio.sh
=> RStudio: avoid hardcoded insecure default password.

tony/tony.sh, tony/validate.sh
Update to tony-cli-0.2.0-all.jar
=> Update Java file version

gpu/README.md, gpu/__init__.py, gpu/gpu_utilization_metrics/create_gpu_metrics.py, gpu/gpu_utilization_metrics/report_gpu_metrics.py, gpu/gpu_utilization_metrics/requirements.txt, gpu/install_gpu_driver.sh, gpu/test_install_gpu_driver.py, integration_tests/dataproc_test_case.py
- Add GPU installation driver support based on current Dataproc documentation
- Add GPU monitoring service via Stackdriver
- Modify dataproc_test_case to handle GPU in master and worker and beta feature
=> Add GPU dataproc initialization and monitoring service

ranger/README.md, ranger/ranger.sh
Added hdfs, hive and yarn plugin, services are preconfigured using Ranger REST API.
=> Initialization action with Apache Ranger.

livy/README.md, livy/test_livy.py, livy/verify_livy_running.py
I created automated check for Livy setup correctness. It creates a session, submit task and check if the task was processed.
You can test this with command: ```python3 -m unittest livy.test_livy``` launched from top project directory.
=> Automated tests for Livy

ranger/__init__.py, ranger/test_ranger.py, ranger/verify_ranger.py
python -m unittest ranger/test_ranger.py
=> Apache Ranger integration test.

solr/test_solr.py, solr/verify_solr.py
python -m unittest solr/test_solr.py
=> Solr integration test.

tony/README.md, tony/tony.sh
=> Add support fro GPU and TF nightly

cloud-sql-proxy/README.MD, cloud-sql-proxy/cloud-sql-proxy.sh
=> Make cloud sql proxy init action work for private IP clusters.

drill/drill.sh
Use last value when zoo.cfg has multiple entries for the same key.
=> Fix ZK connect string calculation for drill init action

kafka/kafka.sh
=> Kafka: wait for ZooKeeper to be up before starting Kafka server

cloud-sql-proxy/cloud-sql-proxy.sh
=> Make usage of private ip disablable

kafka/cruise-control.sh
1) disable metrics anomaly self healing as it is still in development;
2) add ReplicaDistributionGoal for rebalancing after scaling up.
=> Kafka Cruise Control

solr/solr.sh
Installing Solr using Bigtop Debian packages
=> Installing Solr using bigtop debian packages

solr/solr.sh, solr/verify_solr.py
=> Updated Solr directory in test and hdfs configuration in Solr init action.

datalab/datalab.sh
=> Fix Datalab init action for Dataproc 1.0-1.3

starburst-presto/README.MD, starburst-presto/__init__.py, starburst-presto/presto.sh, starburst-presto/test_presto.py
Add Initialization action for Starburst Presto.
The scripts were copied from the initialization action for Presto and modified for Starburst Presto.
=> Starburst Presto

starburst-presto/presto.sh
Update the `jvm.config` in accordance with the current recommended JVM
configuration for Presto.
cc @mattsfuller @ChethanUK
=> Update Presto jvm.config

livy/livy.sh, livy/test_livy.py, livy/verify_livy_running.py
* set wget timeout 30 seconds.
* format and fix lint warnings.
=> Fix flakiness in Livy init action

hbase/hbase.sh, hbase/test_hbase.py
Failure:
```
FAIL: test_hbase_on_gcs.mode: STANDARD.version: 1_2.random_prefix: behd (hbase.test_hbase.HBaseTestCase)
File "/usr/local/google/home/idv/dev/src/dataproc-initialization-actions/hbase/test_hbase.py", line 30, in setUp
self.GCS_BUCKET, stderr))
AssertionError: 1 != 0 : Failed to create bucket test-hbase-20190608-213725-vgdf. Last error: Creating gs://test-hbase-20190608-213725-vgdf/...
BadRequestException: 400 Invalid Value
```
=> Fix HBase integration test

rapids/README.md
A few small fixes for the RAPIDS initialization actions README
=> Fixing RAPIDS README.md rendering, updating URL for example notebook

spark-nlp/README.md, spark-nlp/spark-nlp.sh
This Init Action will allow a user to install spark-nlp on all nodes of a Cloud Dataproc cluster.
spark-nlp: https://github.com/JohnSnowLabs/spark-nlp
=> Adding spark-nlp Init Action (merge ASAP please)

spark-nlp/spark-nlp.sh
Latest Spark NLP version: 2.1.0 https://anaconda.org/JohnSnowLabs/spark-nlp/labels
=> Update Spark NLP to latest version (2.1.0)

conda/bootstrap-conda.sh, conda/test_conda.py
=> Upgrade Conda version to 4.7.10

cloudbuild/presubmit.sh
1. Exclude modified files in the root direcotry from presubmit.
1. Improve presubmit tests output.
=> Fix and improve GCB presubmit

presto/presto.sh
Propose to update presto version for init script.
Pls take a look @blakedubois
=> Update presto to latest version

rstudio/README.MD, rstudio/rstudio.sh
1. Update RStudio server to 1.2.5019 version
2. Use Debian 10 compatible package.
=> Fix RStudio compatibility with Debian 10

datalab/README.md, datalab/datalab.sh
This reverts commit 8998200a4fba3b99ca1a153ad1aad6d4866caae7.
=> Revert "Datalab: add metadata for server port (#699)"

alluxio/README.MD
Update the stale metadata property name.
=> Update Alluxio README.MD

alluxio/alluxio.sh
The Alluxio master and worker roles both start 2 daemons. Each daemon is split into an individual service so that the process lifetime is managed by systemctl independently.
=> Create an individual Alluxio service per daemon

hbase/README.md
=> Update HBase readme

cloud-sql-proxy/cloud-sql-proxy.sh
Redirecting logs to /var/log/cloud-sql-proxy/cloud-sql-proxy.sh.
=> Add log file for cloud-sql-proxy init action

jupyter_sparkmonitor/README.md
Fix typo on creating SparkSession
=> Fix typo on creating SparkSession

presto/README.md
=> Deprecated presto init action

conda/README.md, hbase/README.md, jupyter/README.md, presto/README.md, ranger/README.md, solr/README.md, starburst-presto/README.md, zeppelin/README.md, zookeeper/README.md
These init actions were deprecated in favor of optional components.
=> Add deprecation notices for init actions

python/README.md, python/conda-install.sh
=> [python/conda-install.sh] Support Conda channels configuration

gpu/install_gpu_driver.sh
Increase retry number from 10 to 20 in "execute_with_retries()" method and increase "wget" retry number from 5 to 10.
=> Update install_gpu_driver.sh retry logic to double number of retries

gpu/install_gpu_driver.sh, gpu/test_gpu.py
Fixes NVIDIA-provided driver installation on Debian 10
=> Update GPU init action to use newer version of NVIDIA GPU driver

gpu/install_gpu_driver.sh
Fixes https://github.com/GoogleCloudDataproc/initialization-actions/issues/782
=> [gpu] remove comma from yarn_local_dirs array

rapids/rapids.sh, rapids/test_rapids.py, rapids/verify_rapids_spark.py
- Fixed a bug that prevented xgboost from being found in a PySpark environment
- Modified Spark test to include check for xgboost installation
=> [rapids] Fix XGBoost with PySpark

cloudbuild/run-presubmit-on-k8s.sh
Reduce resources requested for container that triggers/runs tests.
=> Tune k8s presubmit to reduce flakiness

gpu/README.md
=> Added instructions on how to create metrics

gpu/install_gpu_driver.sh
provide option for cuda 11 to support A2 instances
=> [gpu] Provide an option to install CUDA 11 to support GCE A2 instances

prometheus/README.md, prometheus/prometheus.sh
=> [prometheus] Fix Kafka agent download URI

jupyter_sparkmonitor/test_jupyter_sparkmonitor.py, mlvm/README.md, mlvm/test_mlvm.py, rapids/BUILD, rapids/README.md, rapids/rapids.sh, rapids/test_rapids.py, rapids/verify_rapids_spark.py
Fixes after Anaconda component removal from 2.0 images.
=> [rapids][ml] Fix RAPIDS and MLVM init actions on Dataproc 2.0

gpu/install_gpu_driver.sh, rapids/README.md, rapids/rapids.sh, rapids/verify_rapids_spark.py
Updating for RAPIDS Accelerator for Apache Spark 0.2, RAPIDS cudf 0.15 and CUDA 11.  
@mengdong for review
=> [rapids] Versions update: RAPIDS Spark 0.2.0, cuDF 0.15 and CUDA 11

dask/README.md, dask/dask.sh, dask/test_dask.py
- Removed extra exposed variables from init action
- Removed errors in code examples
- Added section on Web UIs
=> [dask] Update readme and clean up init action code

rapids/README.md
Updated cluster create examples, fixed broken hyperlinks
=> [rapids] updating documentation

alluxio/BUILD, alluxio/alluxio.sh, alluxio/test_alluxio.py
=> Update default Alluxio version to 2.4.1

gpu/install_gpu_driver.sh
Fixes compatibility with Linux Kernel 5.9
=> [gpu] Update NVIDIA Debian driver to 455.45.01 version

jupyter/jupyter.sh
Init action fails because of latest nbformat release 5.1
https://github.com/jupyter/nbformat/issues/155
=> [jupyter] Pin nbformat to <5.1 to fix Jupyter init action on 1.3 images

rapids/rapids.sh
Signed-off-by: Sameer Raheja <sraheja@nvidia.com>
cc: @mengdong
=> [rapids] Update to 0.3 version of spark-rapids and 0.17 libcudf

dask/README.md
Changing documentation as optional-component ANACONDA does not works with 'preview' images.
=> [dask] Documentation fix

integration_tests/dataproc_test_case.py, rapids/rapids.sh, rapids/test_rapids.py
Reverts IT framework changes in GoogleCloudDataproc/initialization-actions#852
=> [rapids] Revert image pin in the tests

rapids/rapids.sh
upgrade xgboost spark versions to match v0.3 release from NVIDIA
=> [rapids] Upgrade XGBoost Spark versions

gpu/README.md, gpu/install_gpu_driver.sh, gpu/test_gpu.py
Adds an option for users to install a user-provided version of CUDNN on Ubuntu-based images.
=> [gpu] Add support for NVIDIA cuDNN

rapids/rapids.sh
=> [rapids] Fix default config for Spark 2.x

livy/livy.sh
=> [livy] #871 | Python3 support

gpu/install_gpu_driver.sh
@bradmiro Sorry to bug you, I think your last commit broken spark GPU
=> [gpu] Fix YARN configuration

mlvm/README.md, mlvm/mlvm.sh, mlvm/test_mlvm.py
Adding cuDNN to mlvm documentation, updating libraries.
Running into the same HDFS issue as in https://github.com/GoogleCloudDataproc/initialization-actions/pull/858#issuecomment-768583503
=> [mlvm] Add cuDNN to documentation and update libraries

dask/dask.sh, rapids/rapids.sh, rapids/verify_rapids_dask.py
Bumping dask-yarn from 0.8 to 0.9 to accommodate GPU config. 
Update RAPIDS to include dask-yarn gpu config.
FYI @quasiben, @mengdong, @sameerz
=> [dask][rapids] Updating dask-yarn, rapids for dask-yarn GPU support

rapids/README.md, rapids/rapids.sh, rapids/test_rapids.py
Signed-off-by: Sameer Raheja <sraheja@nvidia.com>
=> Update to RAPIDS Spark 0.5 and 0.19.2

cloudbuild/cloudbuild.yaml, gpu/install_gpu_driver.sh, rapids/test_rapids.py
Add ldconfig after gpu driver installation completes
=> Add ldconfig after gpu driver installation completes (new PR)

rapids/rapids.sh
Change rapids spark version to 21.06.0
=> Change rapids spark version to 21.06.0

connectors/README.md, connectors/connectors.sh, connectors/test_connectors.py
=> [connectors] Remove GCS connector update support

rapids/rapids.sh
Change RAPIDS spark plugin to 21.08
=> [rapids] Upgrade Spark RAPIDS plugin to 21.08

gpu/install_gpu_driver.sh
Fixes https://github.com/GoogleCloudDataproc/initialization-actions/issues/926
=> [gpu] Correct NCCL version

rapids/BUILD, rapids/rapids.sh, rapids/test_rapids.py
- Issue with URL formatting for Spark Jars 
- Added a test for nondefault CUDA versions (related to previous point)
- Added test to confirm dask-cuda-worker is running for Dask + RAPIDS builds
@mengdong @viadea FYI
=> [rapids] fixing url formatting and adding a test for dask-cuda-worker

rapids/rapids.sh
Updating RAPIDS to 21.08.
FYI @mengdong @viadea
=> [rapids] updating RAPIDS to 21.08

mlvm/README.md, mlvm/mlvm.sh, mlvm/test_mlvm.py
- Updated package versions 
- Updated the URL for the Spark-NLP jar
- Deprecated Dataproc 1.5
=> [mlvm] updating package versions, changing spark-nlp source url for jar, deprecate Dataproc 1.5

rapids/rapids.sh
Modify rapids spark to 21.10 from 21.08
=> Modify rapids spark to 21.10 from 21.08

rstudio/rstudio.sh
Repo keys changed in https://cloud.r-project.org/bin/linux/debian/
=> Update rstudio repository keys

rapids/rapids.sh
update spark rapids jars to 21.12
Signed-off-by: Hao Zhu <hazhu@nvidia.com>
=> [rapids] update Spark RAPIDS jars to 21.12

rapids/rapids.sh
Update cudf jar version to 21.12.2
=> [rapids] Update cuDF jar version to 21.12.2

gpu/install_gpu_driver.sh
This PR fixes a bug where device permissions were not set correctly after a node restarts.
=> [gpu] Fix bug where YARN NM could not use GPU after restart

dask/dask.sh, dask/test_dask.py, dask/verify_dask_standalone.py, dask/verify_dask_yarn.py
add dask ml and dask big query
=> [dask] Add dask-ml and dask-bigquery packages by default

datalab/datalab.sh
I can share the testing details which are on internal site.
=> [datalab] Also mount Spark metrics listener jar

gpu/install_gpu_driver.sh, gpu/test_gpu.py
Fixes issue [#987](https://github.com/GoogleCloudDataproc/initialization-actions/issues/987)
=> [gpu] Fix bug where attached GPU resources not available after cluster creation

cloud-sql-proxy/cloud-sql-proxy.sh
Detect Cloud SQL instance type to act on the DB type
Add retries of initialialize metastore db as there race condition in HA can cause failure
Add logging and some code cleanning
=> Enable PostGres as metastore DB.

gpu/install_gpu_driver.sh, gpu/test_gpu.py, rapids/rapids.sh
The pr is to:
- merge #1011 
- update init scripts for spark-rapids v2208 release
- update DMLC from 1.6.1 to 1.6.2
=> [rapids] Update spark-rapids init script for v2208 release

spark-rapids/spark-rapids.sh
update for spark-rapids v2212 release
=> [rapids] Update Spark RAPIDS to 22.12

gpu/install_gpu_driver.sh, rapids/rapids.sh, rapids/test_rapids.py
=> Update to work with dask-rapids 22.10

cloudbuild/run-presubmit-on-k8s.sh
the --requests argument has been deprecated and has now become obsolete
=> removed obsoleted argument

spark-rapids/spark-rapids.sh
update for spark-rapids v2304 release
=> [rapids] Update Spark RAPIDS to v23.04

spark-rapids/spark-rapids.sh
update for spark-rapids v2306 release
=> [rapids] Update Spark RAPIDS to v23.06

spark-rapids/spark-rapids.sh, spark-rapids/test_spark_rapids.py
update xgboost version from 171 to 176 due to https://github.com/dmlc/xgboost/issues/9374
=> update xgboost 171 to 176

kafka/README.md, kafka/kafka-manager.sh, kafka/test_kafka.py
Rebuild CMAK to replace old Kafka Manager
=> Kafka manager outdated. Replacing with CMAK.

oozie/oozie.sh
This PR includes updates that we've found improve the experience for some of our customers.
* declare master_node and ROLE variables in header
* define sample secret name to provide more complete defaults
* create function await_hdfs_datanodes to pause for quorum
* only interact with dfs if quorum has been reached
* moved oozie.service.ProxyUserService.proxyuser.oozie.* property definitions down a few lines
* called out whitepaper recommending these properties
* purge local guava jar and replace it with octets from an https url
=> [oozie] improve support for 2.1 images

livy/README.md, livy/livy.sh
this change should have gone into the previous livy change.
=> [livy] Livy 202301016

rstudio/rstudio.sh
Debian12 (codename bookworm) is not supported in the current version of rstudio init script.
`rstudio-server-2023.09.1-494-amd64.deb` works same as ubuntu22 on debian12 as well.
=> Support debian12 for rstudio installation

spark-rapids/spark-rapids.sh
This PR
- Updates spark-rapids.sh init script with the latest 23.12.1 (to-date) rapids-4-spark version.
=> Update spark rapids version to 23.12.1 

hue/BUILD, hue/run_queries.py, hue/test_hue.py, hue/verify_hue_running.py
Adding the hue test to submit the pyspark job with a python script which verifies, the basic hue functionalities.
=> Enhancement for Hue Init action test

BUILD, spark-rapids/test_spark_rapids.py, spark-rapids/verify_xgboost_spark_rapids.scala, spark-rapids/verify_xgboost_spark_rapids_sql.scala
Expanding the spark rapids test to execute sql queries and adding predictions and accuracy to the xgboost model.
=> Expanding the spark rapids test

datasketches/README.md, datasketches/datasketches.sh, datasketches/pom.xml
Added new initialization action for Apache Datasketches.
=> Added new init action for Datasketches

python/pip-install.sh
Fix the script to fix two scenarios: 
1. No source list file needs to be updated 
2. . Multiple source list files need to be updated
Test result: manually testing done.
=> Fixing pip-install.sh

gpu/README.md, gpu/install_gpu_driver.sh, gpu/test_gpu.py
* Included new functions used to identify OSs better
* Included support for CUDA 12.4 from NVIDIA on 2.0 and 2.1 images, and CUDA 12.0 from Debian on 2.2 images
* new metadata arguments created to allow users to pass signing materials for dkms and mok keys
=> [gpu] Add support for driver signing

gpu/install_gpu_driver.sh
Since the upgrade to kernels which do not allow non-GPL licensing breaks install of ubuntu binary packages, fall back to using nvidia-provided software installers for this platform
=> [gpu] Using Debian branches for Ubuntu driver

cloud-sql-proxy/cloud-sql-proxy.sh
Fix the script to adopt two scenarios:
1. No source list file needs to be updated
2. Multiple source list files need to be updated
=> Fixing cloud-sql-proxy.sh

gpu/install_gpu_driver.sh
* Create a function is_ubuntu22
* create a variable "shortname" from environment which is listed in [1] 
* merged variables NVIDIA_DEBIAN_REPO_URL, NVIDIA_UBUNTU_REPO_URL into NVIDIA_REPO_URL
* enabled the container toolkit repository for ubuntu as well as debian (it is still only installed on debian 12)
[1] https://developer.download.nvidia.com/compute/machine-learning/repos/
=> [gpu] clean up cuda url generation

bigtable/bigtable.sh
Fix the script to fix two scenarios:
1. No source list file needs to be updated
2.  Multiple source list files need to be updated
Test result: manually testing done.
=> Fixing bigtable.sh

dask/dask.sh, dask/test_dask.py
including improvements from work with custom-images repo
=> [dask] merge changes from custom-images

h2o/sample-script.py, h2o/test_h2o.py
The dataset being used previously is no longer available as the bucket being used is now made private. So, in order to resolve this issue, an alternate dataset from a bucket owned by Google is being used , which will ensure that a similar issue is not faced in future.
Tried to make the code changes as minimal and also ensured the same file structure in the bucket as well which was used previously.
=> Replacing the dataset for h2o sample_script to fix tests

gpu/Dockerfile, gpu/install_gpu_driver.sh, gpu/manual-test-runner.sh, gpu/run-bazel-tests.sh, gpu/test_gpu.py, integration_tests/dataproc_test_case.py
Incomplete GPU functionality merits a rollback.
=> roll back PR #1275

cloud-sql-proxy/cloud-sql-proxy.sh, cloud-sql-proxy/test_cloud_sql_proxy.py
* use correct business name
* include contributors in copyright assignment
* include utility functions for comparing running instance to different supported image versions
* include latest implementation of repair_old_backports
* include latest implementation of clean_up_sources_lists
* call clean_up_sources_lists
* unconditionally call repair_old_backports
=> [cloud-sql-proxy] repair apt repositories

cloud-sql-proxy/cloud-sql-proxy.sh
Address issue blocking internal test suite
=> [cloud-sql-proxy] allow for -dev string in bigtop repo directory name

gpu/install_gpu_driver.sh
* enabling GPU agent by default
* for cuda repo, add known signing keys to trustdb
* move variable definition to prepare function
* add some TODO notes for installing this script as a custom image
* spark supports maximum 1 GPU per executor
* printing warning when old cuda is used with ubuntu22
* built a list of PCI devices for each supported GPU type
* improvements to disk usage metrics display
* Supported on 2.0.27-debian10
* * added fallback to using gsutil when gcloud sdk < 402
* * adoptium, cran-r and gcloud pgp databases updated
* * writing multi-valued gpg databases using `gpg --import --no-default-keyring --keyring ...` vice `gpg --dearmor -o`
* * evaluating variable name for keyring path in sources.list file
* driver builds for P4, P100, and V100 now tested
* * build driver from …
=> [gpu] Exercise installer with all supported GPU types

rstudio/rstudio.sh
1. No source list file needs to be updated
2. Multiple source list files need to be updated
=> Fix the script to fix two scenarios:

spark-rapids/spark-rapids.sh
This pr is to update the spark-rapids jar version
=> update spark-rapids version for 25.02 release

cloud-sql-proxy/cloud-sql-proxy.sh, gpu/install_gpu_driver.sh
These fixes were identified while resolving test failures with 1.5-debian10 and 2.2-debian12
=> Test GPU driver installer and cloud-sql-proxy actions with 1.5-debian10

spark-rapids/spark-rapids.sh
This pr is to update the spark-rapids jar version after plugin release
=> update spark-rapids version for 25.04 release

spark-rapids/spark-rapids.sh
This pr is to update the spark-rapids jar version after plugin release
=> update the default spark-rapids version to 2508

cloud-sql-proxy/README.md, cloud-sql-proxy/cloud-sql-proxy.sh
Updated the script to make use of CloudSQL PRoxy V2 binaries
=> Making use of CloudSQL PRoxy V2 binaries and maitaining backward compatibility
